/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.attackprotection;

import com.auth0.client.mgmt.attackprotection.types.UpdateBruteForceSettingsRequestContent;
import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.ManagementApiException;
import com.auth0.client.mgmt.core.ManagementApiHttpResponse;
import com.auth0.client.mgmt.core.ManagementException;
import com.auth0.client.mgmt.core.MediaTypes;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.errors.BadRequestError;
import com.auth0.client.mgmt.errors.ForbiddenError;
import com.auth0.client.mgmt.errors.TooManyRequestsError;
import com.auth0.client.mgmt.errors.UnauthorizedError;
import com.auth0.client.mgmt.types.GetBruteForceSettingsResponseContent;
import com.auth0.client.mgmt.types.UpdateBruteForceSettingsResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawBruteForceProtectionClient {

    protected final ClientOptions clientOptions;

    public AsyncRawBruteForceProtectionClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve details of the Brute-force Protection configuration of your tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetBruteForceSettingsResponseContent>> get() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve details of the Brute-force Protection configuration of your tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetBruteForceSettingsResponseContent>> get(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the Brute-force Protection configuration of your tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateBruteForceSettingsResponseContent>> update() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the Brute-force Protection configuration of your tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateBruteForceSettingsResponseContent>> update(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the Brute-force Protection configuration of your tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateBruteForceSettingsResponseContent>> update(UpdateBruteForceSettingsRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the Brute-force Protection configuration of your tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateBruteForceSettingsResponseContent>> update(UpdateBruteForceSettingsRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
