/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.users.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.types.PreferredAuthenticationMethodEnum;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateUserAuthenticationMethodRequestContent.Builder.class)
public final class UpdateUserAuthenticationMethodRequestContent {

    private final Optional<String> name;

    private final Optional<PreferredAuthenticationMethodEnum> preferredAuthenticationMethod;

    private final Map<String, Object> additionalProperties;

    private UpdateUserAuthenticationMethodRequestContent(Optional<String> name, Optional<PreferredAuthenticationMethodEnum> preferredAuthenticationMethod, Map<String, Object> additionalProperties) {
        this.name = name;
        this.preferredAuthenticationMethod = preferredAuthenticationMethod;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A human-readable label to identify the authentication method.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Preferred phone authentication method
     */
    @JsonProperty("preferred_authentication_method")
    public Optional<PreferredAuthenticationMethodEnum> getPreferredAuthenticationMethod() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(UpdateUserAuthenticationMethodRequestContent other) {
        return name.equals(other.name) && preferredAuthenticationMethod.equals(other.preferredAuthenticationMethod);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> name = Optional.empty();

        private Optional<PreferredAuthenticationMethodEnum> preferredAuthenticationMethod = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(UpdateUserAuthenticationMethodRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>A human-readable label to identify the authentication method.</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder name(String name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Preferred phone authentication method</p>
         */
        @JsonSetter(value = "preferred_authentication_method", nulls = Nulls.SKIP)
        public Builder preferredAuthenticationMethod(Optional<PreferredAuthenticationMethodEnum> preferredAuthenticationMethod) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder preferredAuthenticationMethod(PreferredAuthenticationMethodEnum preferredAuthenticationMethod) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public UpdateUserAuthenticationMethodRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
