/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.roles.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.types.PermissionRequestPayload;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AddRolePermissionsRequestContent.Builder.class)
public final class AddRolePermissionsRequestContent {

    private final List<PermissionRequestPayload> permissions;

    private final Map<String, Object> additionalProperties;

    private AddRolePermissionsRequestContent(List<PermissionRequestPayload> permissions, Map<String, Object> additionalProperties) {
        this.permissions = permissions;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return array of resource_server_identifier, permission_name pairs.
     */
    @JsonProperty("permissions")
    public List<PermissionRequestPayload> getPermissions() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(AddRolePermissionsRequestContent other) {
        return permissions.equals(other.permissions);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private List<PermissionRequestPayload> permissions = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(AddRolePermissionsRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>array of resource_server_identifier, permission_name pairs.</p>
         */
        @JsonSetter(value = "permissions", nulls = Nulls.SKIP)
        public Builder permissions(List<PermissionRequestPayload> permissions) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder addPermissions(PermissionRequestPayload permissions) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder addAllPermissions(List<PermissionRequestPayload> permissions) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public AddRolePermissionsRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
