/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.roles.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AssignRoleUsersRequestContent.Builder.class)
public final class AssignRoleUsersRequestContent {

    private final List<String> users;

    private final Map<String, Object> additionalProperties;

    private AssignRoleUsersRequestContent(List<String> users, Map<String, Object> additionalProperties) {
        this.users = users;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return user_id's of the users to assign the role to.
     */
    @JsonProperty("users")
    public List<String> getUsers() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(AssignRoleUsersRequestContent other) {
        return users.equals(other.users);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private List<String> users = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(AssignRoleUsersRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>user_id's of the users to assign the role to.</p>
         */
        @JsonSetter(value = "users", nulls = Nulls.SKIP)
        public Builder users(List<String> users) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder addUsers(String users) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder addAllUsers(List<String> users) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public AssignRoleUsersRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
