/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.actions;

import com.auth0.client.mgmt.actions.types.ListActionVersionsRequestParameters;
import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.ManagementApiException;
import com.auth0.client.mgmt.core.ManagementApiHttpResponse;
import com.auth0.client.mgmt.core.ManagementException;
import com.auth0.client.mgmt.core.MediaTypes;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.auth0.client.mgmt.core.QueryStringMapper;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.errors.BadRequestError;
import com.auth0.client.mgmt.errors.ForbiddenError;
import com.auth0.client.mgmt.errors.NotFoundError;
import com.auth0.client.mgmt.errors.TooManyRequestsError;
import com.auth0.client.mgmt.errors.UnauthorizedError;
import com.auth0.client.mgmt.types.ActionVersion;
import com.auth0.client.mgmt.types.DeployActionVersionRequestContent;
import com.auth0.client.mgmt.types.DeployActionVersionResponseContent;
import com.auth0.client.mgmt.types.GetActionVersionResponseContent;
import com.auth0.client.mgmt.types.ListActionVersionsPaginatedResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawVersionsClient {

    protected final ClientOptions clientOptions;

    public AsyncRawVersionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionVersion>>> list(String actionId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionVersion>>> list(String actionId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionVersion>>> list(String actionId, ListActionVersionsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionVersion>>> list(String actionId, ListActionVersionsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve a specific version of an action. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetActionVersionResponseContent>> get(String actionId, String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve a specific version of an action. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetActionVersionResponseContent>> get(String actionId, String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public CompletableFuture<ManagementApiHttpResponse<DeployActionVersionResponseContent>> deploy(String actionId, String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public CompletableFuture<ManagementApiHttpResponse<DeployActionVersionResponseContent>> deploy(String actionId, String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public CompletableFuture<ManagementApiHttpResponse<DeployActionVersionResponseContent>> deploy(String actionId, String id, OptionalNullable<DeployActionVersionRequestContent> request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public CompletableFuture<ManagementApiHttpResponse<DeployActionVersionResponseContent>> deploy(String actionId, String id, OptionalNullable<DeployActionVersionRequestContent> request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
