/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.actions;

import com.auth0.client.mgmt.actions.types.ListActionVersionsRequestParameters;
import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.types.ActionVersion;
import com.auth0.client.mgmt.types.DeployActionVersionRequestContent;
import com.auth0.client.mgmt.types.DeployActionVersionResponseContent;
import com.auth0.client.mgmt.types.GetActionVersionResponseContent;

public class VersionsClient {

    protected final ClientOptions clientOptions;

    private final RawVersionsClient rawClient;

    public VersionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawVersionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawVersionsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public SyncPagingIterable<ActionVersion> list(String actionId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public SyncPagingIterable<ActionVersion> list(String actionId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public SyncPagingIterable<ActionVersion> list(String actionId, ListActionVersionsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all of an action's versions. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public SyncPagingIterable<ActionVersion> list(String actionId, ListActionVersionsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve a specific version of an action. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public GetActionVersionResponseContent get(String actionId, String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve a specific version of an action. An action version is created whenever an action is deployed. An action version is immutable, once created.
     */
    public GetActionVersionResponseContent get(String actionId, String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public DeployActionVersionResponseContent deploy(String actionId, String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public DeployActionVersionResponseContent deploy(String actionId, String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public DeployActionVersionResponseContent deploy(String actionId, String id, OptionalNullable<DeployActionVersionRequestContent> request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Performs the equivalent of a roll-back of an action to an earlier, specified version. Creates a new, deployed action version that is identical to the specified version. If this action is currently bound to a trigger, the system will begin executing the newly-created version immediately.
     */
    public DeployActionVersionResponseContent deploy(String actionId, String id, OptionalNullable<DeployActionVersionRequestContent> request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
