/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.actions.modules;

import com.auth0.client.mgmt.actions.modules.types.GetActionModuleVersionsRequestParameters;
import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.ManagementApiException;
import com.auth0.client.mgmt.core.ManagementApiHttpResponse;
import com.auth0.client.mgmt.core.ManagementException;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.QueryStringMapper;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.errors.BadRequestError;
import com.auth0.client.mgmt.errors.ConflictError;
import com.auth0.client.mgmt.errors.ForbiddenError;
import com.auth0.client.mgmt.errors.NotFoundError;
import com.auth0.client.mgmt.errors.PreconditionFailedError;
import com.auth0.client.mgmt.errors.TooManyRequestsError;
import com.auth0.client.mgmt.errors.UnauthorizedError;
import com.auth0.client.mgmt.types.ActionModuleVersion;
import com.auth0.client.mgmt.types.CreateActionModuleVersionResponseContent;
import com.auth0.client.mgmt.types.GetActionModuleVersionResponseContent;
import com.auth0.client.mgmt.types.GetActionModuleVersionsResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawVersionsClient {

    protected final ClientOptions clientOptions;

    public AsyncRawVersionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * List all published versions of a specific Actions Module.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionModuleVersion>>> list(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * List all published versions of a specific Actions Module.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionModuleVersion>>> list(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * List all published versions of a specific Actions Module.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionModuleVersion>>> list(String id, GetActionModuleVersionsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * List all published versions of a specific Actions Module.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<ActionModuleVersion>>> list(String id, GetActionModuleVersionsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Creates a new immutable version of an Actions Module from the current draft version. This publishes the draft as a new version that can be referenced by actions, while maintaining the existing draft for continued development.
     */
    public CompletableFuture<ManagementApiHttpResponse<CreateActionModuleVersionResponseContent>> create(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Creates a new immutable version of an Actions Module from the current draft version. This publishes the draft as a new version that can be referenced by actions, while maintaining the existing draft for continued development.
     */
    public CompletableFuture<ManagementApiHttpResponse<CreateActionModuleVersionResponseContent>> create(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the details of a specific, immutable version of an Actions Module.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetActionModuleVersionResponseContent>> get(String id, String versionId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the details of a specific, immutable version of an Actions Module.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetActionModuleVersionResponseContent>> get(String id, String versionId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
