/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.branding;

import com.auth0.client.mgmt.branding.types.CreateBrandingThemeRequestContent;
import com.auth0.client.mgmt.branding.types.UpdateBrandingThemeRequestContent;
import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.types.CreateBrandingThemeResponseContent;
import com.auth0.client.mgmt.types.GetBrandingDefaultThemeResponseContent;
import com.auth0.client.mgmt.types.GetBrandingThemeResponseContent;
import com.auth0.client.mgmt.types.UpdateBrandingThemeResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncThemesClient {

    protected final ClientOptions clientOptions;

    private final AsyncRawThemesClient rawClient;

    public AsyncThemesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawThemesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawThemesClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create branding theme.
     */
    public CompletableFuture<CreateBrandingThemeResponseContent> create(CreateBrandingThemeRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create branding theme.
     */
    public CompletableFuture<CreateBrandingThemeResponseContent> create(CreateBrandingThemeRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve default branding theme.
     */
    public CompletableFuture<GetBrandingDefaultThemeResponseContent> getDefault() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve default branding theme.
     */
    public CompletableFuture<GetBrandingDefaultThemeResponseContent> getDefault(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve branding theme.
     */
    public CompletableFuture<GetBrandingThemeResponseContent> get(String themeId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve branding theme.
     */
    public CompletableFuture<GetBrandingThemeResponseContent> get(String themeId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete branding theme.
     */
    public CompletableFuture<Void> delete(String themeId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete branding theme.
     */
    public CompletableFuture<Void> delete(String themeId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update branding theme.
     */
    public CompletableFuture<UpdateBrandingThemeResponseContent> update(String themeId, UpdateBrandingThemeRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update branding theme.
     */
    public CompletableFuture<UpdateBrandingThemeResponseContent> update(String themeId, UpdateBrandingThemeRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
