/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.types.EventStreamSubscribeEventsResponseContent;
import com.auth0.client.mgmt.types.SubscribeEventsRequestParameters;
import java.util.concurrent.CompletableFuture;

public class AsyncEventsClient {

    protected final ClientOptions clientOptions;

    private final AsyncRawEventsClient rawClient;

    public AsyncEventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEventsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEventsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Subscribe to events via Server-Sent Events (SSE)
     */
    public CompletableFuture<Iterable<EventStreamSubscribeEventsResponseContent>> subscribe() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Subscribe to events via Server-Sent Events (SSE)
     */
    public CompletableFuture<Iterable<EventStreamSubscribeEventsResponseContent>> subscribe(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Subscribe to events via Server-Sent Events (SSE)
     */
    public CompletableFuture<Iterable<EventStreamSubscribeEventsResponseContent>> subscribe(SubscribeEventsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Subscribe to events via Server-Sent Events (SSE)
     */
    public CompletableFuture<Iterable<EventStreamSubscribeEventsResponseContent>> subscribe(SubscribeEventsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
