/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.types.RulesConfig;
import com.auth0.client.mgmt.types.SetRulesConfigRequestContent;
import com.auth0.client.mgmt.types.SetRulesConfigResponseContent;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncRulesConfigsClient {

    protected final ClientOptions clientOptions;

    private final AsyncRawRulesConfigsClient rawClient;

    public AsyncRulesConfigsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRulesConfigsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRulesConfigsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve rules config variable keys.
     * <pre><code>Note: For security, config variable values cannot be retrieved outside rule execution.
     * </code></pre>
     */
    public CompletableFuture<List<RulesConfig>> list() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve rules config variable keys.
     * <pre><code>Note: For security, config variable values cannot be retrieved outside rule execution.
     * </code></pre>
     */
    public CompletableFuture<List<RulesConfig>> list(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Sets a rules config variable.
     */
    public CompletableFuture<SetRulesConfigResponseContent> set(String key, SetRulesConfigRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Sets a rules config variable.
     */
    public CompletableFuture<SetRulesConfigResponseContent> set(String key, SetRulesConfigRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete a rules config variable identified by its key.
     */
    public CompletableFuture<Void> delete(String key) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete a rules config variable identified by its key.
     */
    public CompletableFuture<Void> delete(String key, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
