/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.types.CreateNetworkAclRequestContent;
import com.auth0.client.mgmt.types.GetNetworkAclsResponseContent;
import com.auth0.client.mgmt.types.ListNetworkAclsRequestParameters;
import com.auth0.client.mgmt.types.NetworkAclsResponseContent;
import com.auth0.client.mgmt.types.SetNetworkAclRequestContent;
import com.auth0.client.mgmt.types.SetNetworkAclsResponseContent;
import com.auth0.client.mgmt.types.UpdateNetworkAclRequestContent;
import com.auth0.client.mgmt.types.UpdateNetworkAclResponseContent;

public class NetworkAclsClient {

    protected final ClientOptions clientOptions;

    private final RawNetworkAclsClient rawClient;

    public NetworkAclsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawNetworkAclsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawNetworkAclsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Get all access control list entries for your client.
     */
    public SyncPagingIterable<NetworkAclsResponseContent> list() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Get all access control list entries for your client.
     */
    public SyncPagingIterable<NetworkAclsResponseContent> list(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Get all access control list entries for your client.
     */
    public SyncPagingIterable<NetworkAclsResponseContent> list(ListNetworkAclsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Get all access control list entries for your client.
     */
    public SyncPagingIterable<NetworkAclsResponseContent> list(ListNetworkAclsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create a new access control list for your client.
     */
    public void create(CreateNetworkAclRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create a new access control list for your client.
     */
    public void create(CreateNetworkAclRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Get a specific access control list entry for your client.
     */
    public GetNetworkAclsResponseContent get(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Get a specific access control list entry for your client.
     */
    public GetNetworkAclsResponseContent get(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update existing access control list for your client.
     */
    public SetNetworkAclsResponseContent set(String id, SetNetworkAclRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update existing access control list for your client.
     */
    public SetNetworkAclsResponseContent set(String id, SetNetworkAclRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete existing access control list for your client.
     */
    public void delete(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete existing access control list for your client.
     */
    public void delete(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update existing access control list for your client.
     */
    public UpdateNetworkAclResponseContent update(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update existing access control list for your client.
     */
    public UpdateNetworkAclResponseContent update(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update existing access control list for your client.
     */
    public UpdateNetworkAclResponseContent update(String id, UpdateNetworkAclRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update existing access control list for your client.
     */
    public UpdateNetworkAclResponseContent update(String id, UpdateNetworkAclRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
