/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.organizations.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListOrganizationClientGrantsRequestParameters.Builder.class)
public final class ListOrganizationClientGrantsRequestParameters {

    private final Optional<List<String>> grantIds;

    private final OptionalNullable<String> audience;

    private final OptionalNullable<String> clientId;

    private final OptionalNullable<Integer> page;

    private final OptionalNullable<Integer> perPage;

    private final OptionalNullable<Boolean> includeTotals;

    private final Map<String, Object> additionalProperties;

    private ListOrganizationClientGrantsRequestParameters(Optional<List<String>> grantIds, OptionalNullable<String> audience, OptionalNullable<String> clientId, OptionalNullable<Integer> page, OptionalNullable<Integer> perPage, OptionalNullable<Boolean> includeTotals, Map<String, Object> additionalProperties) {
        this.grantIds = grantIds;
        this.audience = audience;
        this.clientId = clientId;
        this.page = page;
        this.perPage = perPage;
        this.includeTotals = includeTotals;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Optional filter on the ID of the client grant. Must be URL encoded and may be specified multiple times (max 10).<b>e.g.</b> <i>../client-grants?grant_ids=id1&amp;grant_ids=id2</i>
     */
    @JsonIgnore
    public Optional<List<String>> getGrantIds() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Optional filter on audience of the client grant.
     */
    @JsonIgnore
    public OptionalNullable<String> getAudience() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Optional filter on client_id of the client grant.
     */
    @JsonIgnore
    public OptionalNullable<String> getClientId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Page index of the results to return. First page is 0.
     */
    @JsonIgnore
    public OptionalNullable<Integer> getPage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Number of results per page. Defaults to 50.
     */
    @JsonIgnore
    public OptionalNullable<Integer> getPerPage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Return results inside an object that contains the total result count (true) or as a direct array of results (false, default).
     */
    @JsonIgnore
    public OptionalNullable<Boolean> getIncludeTotals() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ListOrganizationClientGrantsRequestParameters other) {
        return grantIds.equals(other.grantIds) && audience.equals(other.audience) && clientId.equals(other.clientId) && page.equals(other.page) && perPage.equals(other.perPage) && includeTotals.equals(other.includeTotals);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<List<String>> grantIds = Optional.empty();

        private OptionalNullable<String> audience = OptionalNullable.absent();

        private OptionalNullable<String> clientId = OptionalNullable.absent();

        private OptionalNullable<Integer> page = OptionalNullable.absent();

        private OptionalNullable<Integer> perPage = OptionalNullable.absent();

        private OptionalNullable<Boolean> includeTotals = OptionalNullable.absent();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(ListOrganizationClientGrantsRequestParameters other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Optional filter on the ID of the client grant. Must be URL encoded and may be specified multiple times (max 10).<b>e.g.</b> <i>../client-grants?grant_ids=id1&amp;grant_ids=id2</i></p>
         */
        @JsonSetter(value = "grant_ids", nulls = Nulls.SKIP)
        public Builder grantIds(@Nullable Optional<List<String>> grantIds) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder grantIds(List<String> grantIds) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder grantIds(com.auth0.client.mgmt.core.Nullable<List<String>> grantIds) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder grantIds(String grantIds) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Optional filter on audience of the client grant.</p>
         */
        @JsonSetter(value = "audience", nulls = Nulls.SKIP)
        public Builder audience(@Nullable OptionalNullable<String> audience) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder audience(String audience) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder audience(Optional<String> audience) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder audience(com.auth0.client.mgmt.core.Nullable<String> audience) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Optional filter on client_id of the client grant.</p>
         */
        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(@Nullable OptionalNullable<String> clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder clientId(String clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder clientId(Optional<String> clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder clientId(com.auth0.client.mgmt.core.Nullable<String> clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Page index of the results to return. First page is 0.</p>
         */
        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(@Nullable OptionalNullable<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(Integer page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(Optional<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(com.auth0.client.mgmt.core.Nullable<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Number of results per page. Defaults to 50.</p>
         */
        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(@Nullable OptionalNullable<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(Integer perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(Optional<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(com.auth0.client.mgmt.core.Nullable<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Return results inside an object that contains the total result count (true) or as a direct array of results (false, default).</p>
         */
        @JsonSetter(value = "include_totals", nulls = Nulls.SKIP)
        public Builder includeTotals(@Nullable OptionalNullable<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(Boolean includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(Optional<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(com.auth0.client.mgmt.core.Nullable<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public ListOrganizationClientGrantsRequestParameters build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
