/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ActionTriggerTypeEnum {

    public static final ActionTriggerTypeEnum PASSWORD_RESET_POST_CHALLENGE = new ActionTriggerTypeEnum(Value.PASSWORD_RESET_POST_CHALLENGE, "password-reset-post-challenge");

    public static final ActionTriggerTypeEnum SIGNUP_POST_IDENTIFIER = new ActionTriggerTypeEnum(Value.SIGNUP_POST_IDENTIFIER, "signup-post-identifier");

    public static final ActionTriggerTypeEnum CUSTOM_PHONE_PROVIDER = new ActionTriggerTypeEnum(Value.CUSTOM_PHONE_PROVIDER, "custom-phone-provider");

    public static final ActionTriggerTypeEnum CUSTOM_EMAIL_PROVIDER = new ActionTriggerTypeEnum(Value.CUSTOM_EMAIL_PROVIDER, "custom-email-provider");

    public static final ActionTriggerTypeEnum PRE_USER_REGISTRATION = new ActionTriggerTypeEnum(Value.PRE_USER_REGISTRATION, "pre-user-registration");

    public static final ActionTriggerTypeEnum LOGIN_POST_IDENTIFIER = new ActionTriggerTypeEnum(Value.LOGIN_POST_IDENTIFIER, "login-post-identifier");

    public static final ActionTriggerTypeEnum POST_USER_REGISTRATION = new ActionTriggerTypeEnum(Value.POST_USER_REGISTRATION, "post-user-registration");

    public static final ActionTriggerTypeEnum PASSWORD_HASH_MIGRATION = new ActionTriggerTypeEnum(Value.PASSWORD_HASH_MIGRATION, "password-hash-migration");

    public static final ActionTriggerTypeEnum CREDENTIALS_EXCHANGE = new ActionTriggerTypeEnum(Value.CREDENTIALS_EXCHANGE, "credentials-exchange");

    public static final ActionTriggerTypeEnum CUSTOM_TOKEN_EXCHANGE = new ActionTriggerTypeEnum(Value.CUSTOM_TOKEN_EXCHANGE, "custom-token-exchange");

    public static final ActionTriggerTypeEnum POST_CHANGE_PASSWORD = new ActionTriggerTypeEnum(Value.POST_CHANGE_PASSWORD, "post-change-password");

    public static final ActionTriggerTypeEnum SEND_PHONE_MESSAGE = new ActionTriggerTypeEnum(Value.SEND_PHONE_MESSAGE, "send-phone-message");

    public static final ActionTriggerTypeEnum EVENT_STREAM = new ActionTriggerTypeEnum(Value.EVENT_STREAM, "event-stream");

    public static final ActionTriggerTypeEnum POST_LOGIN = new ActionTriggerTypeEnum(Value.POST_LOGIN, "post-login");

    private final Value value;

    private final String string;

    ActionTriggerTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ActionTriggerTypeEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        POST_LOGIN,
        CREDENTIALS_EXCHANGE,
        PRE_USER_REGISTRATION,
        POST_USER_REGISTRATION,
        POST_CHANGE_PASSWORD,
        SEND_PHONE_MESSAGE,
        CUSTOM_PHONE_PROVIDER,
        CUSTOM_EMAIL_PROVIDER,
        PASSWORD_RESET_POST_CHALLENGE,
        CUSTOM_TOKEN_EXCHANGE,
        EVENT_STREAM,
        PASSWORD_HASH_MIGRATION,
        LOGIN_POST_IDENTIFIER,
        SIGNUP_POST_IDENTIFIER,
        UNKNOWN
    }

    public interface Visitor<T> {

        T visitPostLogin();

        T visitCredentialsExchange();

        T visitPreUserRegistration();

        T visitPostUserRegistration();

        T visitPostChangePassword();

        T visitSendPhoneMessage();

        T visitCustomPhoneProvider();

        T visitCustomEmailProvider();

        T visitPasswordResetPostChallenge();

        T visitCustomTokenExchange();

        T visitEventStream();

        T visitPasswordHashMigration();

        T visitLoginPostIdentifier();

        T visitSignupPostIdentifier();

        T visitUnknown(String unknownType);
    }
}
