/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ActionTrigger.Builder.class)
public final class ActionTrigger {

    private final ActionTriggerTypeEnum id;

    private final Optional<String> version;

    private final Optional<String> status;

    private final Optional<List<String>> runtimes;

    private final Optional<String> defaultRuntime;

    private final Optional<List<ActionTriggerCompatibleTrigger>> compatibleTriggers;

    private final Optional<ActionBindingTypeEnum> bindingPolicy;

    private final Map<String, Object> additionalProperties;

    private ActionTrigger(ActionTriggerTypeEnum id, Optional<String> version, Optional<String> status, Optional<List<String>> runtimes, Optional<String> defaultRuntime, Optional<List<ActionTriggerCompatibleTrigger>> compatibleTriggers, Optional<ActionBindingTypeEnum> bindingPolicy, Map<String, Object> additionalProperties) {
        this.id = id;
        this.version = version;
        this.status = status;
        this.runtimes = runtimes;
        this.defaultRuntime = defaultRuntime;
        this.compatibleTriggers = compatibleTriggers;
        this.bindingPolicy = bindingPolicy;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public ActionTriggerTypeEnum getId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return The version of a trigger. v1, v2, etc.
     */
    @JsonProperty("version")
    public Optional<String> getVersion() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return status points to the trigger status.
     */
    @JsonProperty("status")
    public Optional<String> getStatus() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return runtimes supported by this trigger.
     */
    @JsonProperty("runtimes")
    public Optional<List<String>> getRuntimes() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Runtime that will be used when none is specified when creating an action.
     */
    @JsonProperty("default_runtime")
    public Optional<String> getDefaultRuntime() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return compatible_triggers informs which other trigger supports the same event and api.
     */
    @JsonProperty("compatible_triggers")
    public Optional<List<ActionTriggerCompatibleTrigger>> getCompatibleTriggers() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("binding_policy")
    public Optional<ActionBindingTypeEnum> getBindingPolicy() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ActionTrigger other) {
        return id.equals(other.id) && version.equals(other.version) && status.equals(other.status) && runtimes.equals(other.runtimes) && defaultRuntime.equals(other.defaultRuntime) && compatibleTriggers.equals(other.compatibleTriggers) && bindingPolicy.equals(other.bindingPolicy);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static IdStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface IdStage {

        _FinalStage id(@NotNull ActionTriggerTypeEnum id);

        Builder from(ActionTrigger other);
    }

    public interface _FinalStage {

        ActionTrigger build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The version of a trigger. v1, v2, etc.</p>
         */
        _FinalStage version(Optional<String> version);

        _FinalStage version(String version);

        /**
         * <p>status points to the trigger status.</p>
         */
        _FinalStage status(Optional<String> status);

        _FinalStage status(String status);

        /**
         * <p>runtimes supported by this trigger.</p>
         */
        _FinalStage runtimes(Optional<List<String>> runtimes);

        _FinalStage runtimes(List<String> runtimes);

        /**
         * <p>Runtime that will be used when none is specified when creating an action.</p>
         */
        _FinalStage defaultRuntime(Optional<String> defaultRuntime);

        _FinalStage defaultRuntime(String defaultRuntime);

        /**
         * <p>compatible_triggers informs which other trigger supports the same event and api.</p>
         */
        _FinalStage compatibleTriggers(Optional<List<ActionTriggerCompatibleTrigger>> compatibleTriggers);

        _FinalStage compatibleTriggers(List<ActionTriggerCompatibleTrigger> compatibleTriggers);

        _FinalStage bindingPolicy(Optional<ActionBindingTypeEnum> bindingPolicy);

        _FinalStage bindingPolicy(ActionBindingTypeEnum bindingPolicy);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, _FinalStage {

        private ActionTriggerTypeEnum id;

        private Optional<ActionBindingTypeEnum> bindingPolicy = Optional.empty();

        private Optional<List<ActionTriggerCompatibleTrigger>> compatibleTriggers = Optional.empty();

        private Optional<String> defaultRuntime = Optional.empty();

        private Optional<List<String>> runtimes = Optional.empty();

        private Optional<String> status = Optional.empty();

        private Optional<String> version = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(ActionTrigger other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("id")
        public _FinalStage id(@NotNull ActionTriggerTypeEnum id) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage bindingPolicy(ActionBindingTypeEnum bindingPolicy) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "binding_policy", nulls = Nulls.SKIP)
        public _FinalStage bindingPolicy(Optional<ActionBindingTypeEnum> bindingPolicy) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>compatible_triggers informs which other trigger supports the same event and api.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage compatibleTriggers(List<ActionTriggerCompatibleTrigger> compatibleTriggers) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>compatible_triggers informs which other trigger supports the same event and api.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "compatible_triggers", nulls = Nulls.SKIP)
        public _FinalStage compatibleTriggers(Optional<List<ActionTriggerCompatibleTrigger>> compatibleTriggers) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Runtime that will be used when none is specified when creating an action.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage defaultRuntime(String defaultRuntime) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Runtime that will be used when none is specified when creating an action.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "default_runtime", nulls = Nulls.SKIP)
        public _FinalStage defaultRuntime(Optional<String> defaultRuntime) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>runtimes supported by this trigger.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage runtimes(List<String> runtimes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>runtimes supported by this trigger.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "runtimes", nulls = Nulls.SKIP)
        public _FinalStage runtimes(Optional<List<String>> runtimes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>status points to the trigger status.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(String status) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>status points to the trigger status.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<String> status) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The version of a trigger. v1, v2, etc.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage version(String version) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The version of a trigger. v1, v2, etc.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "version", nulls = Nulls.SKIP)
        public _FinalStage version(Optional<String> version) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public ActionTrigger build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
