/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AttackProtectionCaptchaRecaptchaEnterpriseResponseContent.Builder.class)
public final class AttackProtectionCaptchaRecaptchaEnterpriseResponseContent {

    private final Optional<String> siteKey;

    private final Optional<String> projectId;

    private final Map<String, Object> additionalProperties;

    private AttackProtectionCaptchaRecaptchaEnterpriseResponseContent(Optional<String> siteKey, Optional<String> projectId, Map<String, Object> additionalProperties) {
        this.siteKey = siteKey;
        this.projectId = projectId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The site key for the reCAPTCHA Enterprise provider.
     */
    @JsonProperty("site_key")
    public Optional<String> getSiteKey() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return The project ID for the reCAPTCHA Enterprise provider.
     */
    @JsonProperty("project_id")
    public Optional<String> getProjectId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(AttackProtectionCaptchaRecaptchaEnterpriseResponseContent other) {
        return siteKey.equals(other.siteKey) && projectId.equals(other.projectId);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> siteKey = Optional.empty();

        private Optional<String> projectId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(AttackProtectionCaptchaRecaptchaEnterpriseResponseContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The site key for the reCAPTCHA Enterprise provider.</p>
         */
        @JsonSetter(value = "site_key", nulls = Nulls.SKIP)
        public Builder siteKey(Optional<String> siteKey) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder siteKey(String siteKey) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The project ID for the reCAPTCHA Enterprise provider.</p>
         */
        @JsonSetter(value = "project_id", nulls = Nulls.SKIP)
        public Builder projectId(Optional<String> projectId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder projectId(String projectId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public AttackProtectionCaptchaRecaptchaEnterpriseResponseContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
