/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BadRequestSchema.Builder.class)
public final class BadRequestSchema {

    private final String message;

    private final String statusCode;

    private final BadRequestSchemaError error;

    private final Map<String, Object> additionalProperties;

    private BadRequestSchema(String message, String statusCode, BadRequestSchemaError error, Map<String, Object> additionalProperties) {
        this.message = message;
        this.statusCode = statusCode;
        this.error = error;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("message")
    public String getMessage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("statusCode")
    public String getStatusCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("error")
    public BadRequestSchemaError getError() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(BadRequestSchema other) {
        return message.equals(other.message) && statusCode.equals(other.statusCode) && error.equals(other.error);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static MessageStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface MessageStage {

        StatusCodeStage message(@NotNull String message);

        Builder from(BadRequestSchema other);
    }

    public interface StatusCodeStage {

        ErrorStage statusCode(@NotNull String statusCode);
    }

    public interface ErrorStage {

        _FinalStage error(@NotNull BadRequestSchemaError error);
    }

    public interface _FinalStage {

        BadRequestSchema build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MessageStage, StatusCodeStage, ErrorStage, _FinalStage {

        private String message;

        private String statusCode;

        private BadRequestSchemaError error;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(BadRequestSchema other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("message")
        public StatusCodeStage message(@NotNull String message) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("statusCode")
        public ErrorStage statusCode(@NotNull String statusCode) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("error")
        public _FinalStage error(@NotNull BadRequestSchemaError error) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public BadRequestSchema build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
