/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BrandingThemeWidgetHeaderTextAlignmentEnum {

    public static final BrandingThemeWidgetHeaderTextAlignmentEnum LEFT = new BrandingThemeWidgetHeaderTextAlignmentEnum(Value.LEFT, "left");

    public static final BrandingThemeWidgetHeaderTextAlignmentEnum RIGHT = new BrandingThemeWidgetHeaderTextAlignmentEnum(Value.RIGHT, "right");

    public static final BrandingThemeWidgetHeaderTextAlignmentEnum CENTER = new BrandingThemeWidgetHeaderTextAlignmentEnum(Value.CENTER, "center");

    private final Value value;

    private final String string;

    BrandingThemeWidgetHeaderTextAlignmentEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BrandingThemeWidgetHeaderTextAlignmentEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        CENTER, LEFT, RIGHT, UNKNOWN
    }

    public interface Visitor<T> {

        T visitCenter();

        T visitLeft();

        T visitRight();

        T visitUnknown(String unknownType);
    }
}
