/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CertificateSubjectDnCredentialTypeEnum {

    public static final CertificateSubjectDnCredentialTypeEnum CERT_SUBJECT_DN = new CertificateSubjectDnCredentialTypeEnum(Value.CERT_SUBJECT_DN, "cert_subject_dn");

    private final Value value;

    private final String string;

    CertificateSubjectDnCredentialTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CertificateSubjectDnCredentialTypeEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        CERT_SUBJECT_DN, UNKNOWN
    }

    public interface Visitor<T> {

        T visitCertSubjectDn();

        T visitUnknown(String unknownType);
    }
}
