/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ChangePasswordTicketRequestContent.Builder.class)
public final class ChangePasswordTicketRequestContent {

    private final Optional<String> resultUrl;

    private final Optional<String> userId;

    private final Optional<String> clientId;

    private final Optional<String> organizationId;

    private final Optional<String> connectionId;

    private final Optional<String> email;

    private final Optional<Integer> ttlSec;

    private final Optional<Boolean> markEmailAsVerified;

    private final Optional<Boolean> includeEmailInRedirect;

    private final Optional<ChangePasswordTicketIdentity> identity;

    private final Map<String, Object> additionalProperties;

    private ChangePasswordTicketRequestContent(Optional<String> resultUrl, Optional<String> userId, Optional<String> clientId, Optional<String> organizationId, Optional<String> connectionId, Optional<String> email, Optional<Integer> ttlSec, Optional<Boolean> markEmailAsVerified, Optional<Boolean> includeEmailInRedirect, Optional<ChangePasswordTicketIdentity> identity, Map<String, Object> additionalProperties) {
        this.resultUrl = resultUrl;
        this.userId = userId;
        this.clientId = clientId;
        this.organizationId = organizationId;
        this.connectionId = connectionId;
        this.email = email;
        this.ttlSec = ttlSec;
        this.markEmailAsVerified = markEmailAsVerified;
        this.includeEmailInRedirect = includeEmailInRedirect;
        this.identity = identity;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return URL the user will be redirected to in the classic Universal Login experience once the ticket is used. Cannot be specified when using organization_id. May be specified together with client_id when the tenant has a custom password reset page enabled and a password-reset-post-challenge Action bound.
     */
    @JsonProperty("result_url")
    public Optional<String> getResultUrl() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return user_id of for whom the ticket should be created.
     */
    @JsonProperty("user_id")
    public Optional<String> getUserId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return ID of the client (application). If provided for tenants using the New Universal Login experience, the email template and UI displays application details, and the user is prompted to redirect to the application's <a target='' href='https://auth0.com/docs/authenticate/login/auth0-universal-login/configure-default-login-routes#completing-the-password-reset-flow'>default login route</a> after the ticket is used. client_id is required to use the <a target='' href='https://auth0.com/docs/customize/actions/flows-and-triggers/post-change-password-flow'>Password Reset Post Challenge</a> trigger.
     */
    @JsonProperty("client_id")
    public Optional<String> getClientId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return (Optional) Organization ID – the ID of the Organization. If provided, organization parameters will be made available to the email template and organization branding will be applied to the prompt. In addition, the redirect link in the prompt will include organization_id and organization_name query string parameters.
     */
    @JsonProperty("organization_id")
    public Optional<String> getOrganizationId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return ID of the connection. If provided, allows the user to be specified using email instead of user_id. If you set this value, you must also send the email parameter. You cannot send user_id when specifying a connection_id.
     */
    @JsonProperty("connection_id")
    public Optional<String> getConnectionId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Email address of the user for whom the tickets should be created. Requires the connection_id parameter. Cannot be specified when using user_id.
     */
    @JsonProperty("email")
    public Optional<String> getEmail() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Number of seconds for which the ticket is valid before expiration. If unspecified or set to 0, this value defaults to 432000 seconds (5 days).
     */
    @JsonProperty("ttl_sec")
    public Optional<Integer> getTtlSec() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Whether to set the email_verified attribute to true (true) or whether it should not be updated (false).
     */
    @JsonProperty("mark_email_as_verified")
    public Optional<Boolean> getMarkEmailAsVerified() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Whether to include the email address as part of the returnUrl in the reset_email (true), or not (false).
     */
    @JsonProperty("includeEmailInRedirect")
    public Optional<Boolean> getIncludeEmailInRedirect() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("identity")
    public Optional<ChangePasswordTicketIdentity> getIdentity() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ChangePasswordTicketRequestContent other) {
        return resultUrl.equals(other.resultUrl) && userId.equals(other.userId) && clientId.equals(other.clientId) && organizationId.equals(other.organizationId) && connectionId.equals(other.connectionId) && email.equals(other.email) && ttlSec.equals(other.ttlSec) && markEmailAsVerified.equals(other.markEmailAsVerified) && includeEmailInRedirect.equals(other.includeEmailInRedirect) && identity.equals(other.identity);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> resultUrl = Optional.empty();

        private Optional<String> userId = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<String> organizationId = Optional.empty();

        private Optional<String> connectionId = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<Integer> ttlSec = Optional.empty();

        private Optional<Boolean> markEmailAsVerified = Optional.empty();

        private Optional<Boolean> includeEmailInRedirect = Optional.empty();

        private Optional<ChangePasswordTicketIdentity> identity = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(ChangePasswordTicketRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>URL the user will be redirected to in the classic Universal Login experience once the ticket is used. Cannot be specified when using organization_id. May be specified together with client_id when the tenant has a custom password reset page enabled and a password-reset-post-challenge Action bound.</p>
         */
        @JsonSetter(value = "result_url", nulls = Nulls.SKIP)
        public Builder resultUrl(Optional<String> resultUrl) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder resultUrl(String resultUrl) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>user_id of for whom the ticket should be created.</p>
         */
        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder userId(String userId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>ID of the client (application). If provided for tenants using the New Universal Login experience, the email template and UI displays application details, and the user is prompted to redirect to the application's <a target='' href='https://auth0.com/docs/authenticate/login/auth0-universal-login/configure-default-login-routes#completing-the-password-reset-flow'>default login route</a> after the ticket is used. client_id is required to use the <a target='' href='https://auth0.com/docs/customize/actions/flows-and-triggers/post-change-password-flow'>Password Reset Post Challenge</a> trigger.</p>
         */
        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder clientId(String clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>(Optional) Organization ID – the ID of the Organization. If provided, organization parameters will be made available to the email template and organization branding will be applied to the prompt. In addition, the redirect link in the prompt will include organization_id and organization_name query string parameters.</p>
         */
        @JsonSetter(value = "organization_id", nulls = Nulls.SKIP)
        public Builder organizationId(Optional<String> organizationId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder organizationId(String organizationId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>ID of the connection. If provided, allows the user to be specified using email instead of user_id. If you set this value, you must also send the email parameter. You cannot send user_id when specifying a connection_id.</p>
         */
        @JsonSetter(value = "connection_id", nulls = Nulls.SKIP)
        public Builder connectionId(Optional<String> connectionId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder connectionId(String connectionId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Email address of the user for whom the tickets should be created. Requires the connection_id parameter. Cannot be specified when using user_id.</p>
         */
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public Builder email(Optional<String> email) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder email(String email) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Number of seconds for which the ticket is valid before expiration. If unspecified or set to 0, this value defaults to 432000 seconds (5 days).</p>
         */
        @JsonSetter(value = "ttl_sec", nulls = Nulls.SKIP)
        public Builder ttlSec(Optional<Integer> ttlSec) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder ttlSec(Integer ttlSec) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Whether to set the email_verified attribute to true (true) or whether it should not be updated (false).</p>
         */
        @JsonSetter(value = "mark_email_as_verified", nulls = Nulls.SKIP)
        public Builder markEmailAsVerified(Optional<Boolean> markEmailAsVerified) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder markEmailAsVerified(Boolean markEmailAsVerified) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Whether to include the email address as part of the returnUrl in the reset_email (true), or not (false).</p>
         */
        @JsonSetter(value = "includeEmailInRedirect", nulls = Nulls.SKIP)
        public Builder includeEmailInRedirect(Optional<Boolean> includeEmailInRedirect) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeEmailInRedirect(Boolean includeEmailInRedirect) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "identity", nulls = Nulls.SKIP)
        public Builder identity(Optional<ChangePasswordTicketIdentity> identity) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder identity(ChangePasswordTicketIdentity identity) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public ChangePasswordTicketRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
