/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientSessionTransferDeviceBindingEnum {

    public static final ClientSessionTransferDeviceBindingEnum ASN = new ClientSessionTransferDeviceBindingEnum(Value.ASN, "asn");

    public static final ClientSessionTransferDeviceBindingEnum IP = new ClientSessionTransferDeviceBindingEnum(Value.IP, "ip");

    public static final ClientSessionTransferDeviceBindingEnum NONE = new ClientSessionTransferDeviceBindingEnum(Value.NONE, "none");

    private final Value value;

    private final String string;

    ClientSessionTransferDeviceBindingEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientSessionTransferDeviceBindingEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        IP, ASN, NONE, UNKNOWN
    }

    public interface Visitor<T> {

        T visitIp();

        T visitAsn();

        T visitNone();

        T visitUnknown(String unknownType);
    }
}
