/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClientJwtConfiguration.Builder.class)
public final class ClientJwtConfiguration {

    private final Optional<Integer> lifetimeInSeconds;

    private final Optional<Boolean> secretEncoded;

    private final Optional<Map<String, Object>> scopes;

    private final Optional<SigningAlgorithmEnum> alg;

    private final Map<String, Object> additionalProperties;

    private ClientJwtConfiguration(Optional<Integer> lifetimeInSeconds, Optional<Boolean> secretEncoded, Optional<Map<String, Object>> scopes, Optional<SigningAlgorithmEnum> alg, Map<String, Object> additionalProperties) {
        this.lifetimeInSeconds = lifetimeInSeconds;
        this.secretEncoded = secretEncoded;
        this.scopes = scopes;
        this.alg = alg;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Number of seconds the JWT will be valid for (affects <code>exp</code> claim).
     */
    @JsonProperty("lifetime_in_seconds")
    public Optional<Integer> getLifetimeInSeconds() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Whether the client secret is base64 encoded (true) or unencoded (false).
     */
    @JsonProperty("secret_encoded")
    public Optional<Boolean> getSecretEncoded() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("scopes")
    public Optional<Map<String, Object>> getScopes() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("alg")
    public Optional<SigningAlgorithmEnum> getAlg() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ClientJwtConfiguration other) {
        return lifetimeInSeconds.equals(other.lifetimeInSeconds) && secretEncoded.equals(other.secretEncoded) && scopes.equals(other.scopes) && alg.equals(other.alg);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<Integer> lifetimeInSeconds = Optional.empty();

        private Optional<Boolean> secretEncoded = Optional.empty();

        private Optional<Map<String, Object>> scopes = Optional.empty();

        private Optional<SigningAlgorithmEnum> alg = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(ClientJwtConfiguration other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Number of seconds the JWT will be valid for (affects <code>exp</code> claim).</p>
         */
        @JsonSetter(value = "lifetime_in_seconds", nulls = Nulls.SKIP)
        public Builder lifetimeInSeconds(Optional<Integer> lifetimeInSeconds) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder lifetimeInSeconds(Integer lifetimeInSeconds) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Whether the client secret is base64 encoded (true) or unencoded (false).</p>
         */
        @JsonSetter(value = "secret_encoded", nulls = Nulls.SKIP)
        public Builder secretEncoded(Optional<Boolean> secretEncoded) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder secretEncoded(Boolean secretEncoded) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "scopes", nulls = Nulls.SKIP)
        public Builder scopes(Optional<Map<String, Object>> scopes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder scopes(Map<String, Object> scopes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "alg", nulls = Nulls.SKIP)
        public Builder alg(Optional<SigningAlgorithmEnum> alg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder alg(SigningAlgorithmEnum alg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public ClientJwtConfiguration build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
