/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientThirdPartySecurityModeEnum {

    public static final ClientThirdPartySecurityModeEnum PERMISSIVE = new ClientThirdPartySecurityModeEnum(Value.PERMISSIVE, "permissive");

    public static final ClientThirdPartySecurityModeEnum STRICT = new ClientThirdPartySecurityModeEnum(Value.STRICT, "strict");

    private final Value value;

    private final String string;

    ClientThirdPartySecurityModeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientThirdPartySecurityModeEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        STRICT, PERMISSIVE, UNKNOWN
    }

    public interface Visitor<T> {

        T visitStrict();

        T visitPermissive();

        T visitUnknown(String unknownType);
    }
}
