/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ConnectionUpstreamAliasEnum {

    public static final ConnectionUpstreamAliasEnum CLIENT_ID = new ConnectionUpstreamAliasEnum(Value.CLIENT_ID, "client_id");

    public static final ConnectionUpstreamAliasEnum UI_LOCALES = new ConnectionUpstreamAliasEnum(Value.UI_LOCALES, "ui_locales");

    public static final ConnectionUpstreamAliasEnum ACR_VALUES = new ConnectionUpstreamAliasEnum(Value.ACR_VALUES, "acr_values");

    public static final ConnectionUpstreamAliasEnum AUDIENCE = new ConnectionUpstreamAliasEnum(Value.AUDIENCE, "audience");

    public static final ConnectionUpstreamAliasEnum LOGIN_HINT = new ConnectionUpstreamAliasEnum(Value.LOGIN_HINT, "login_hint");

    public static final ConnectionUpstreamAliasEnum RESPONSE_TYPE = new ConnectionUpstreamAliasEnum(Value.RESPONSE_TYPE, "response_type");

    public static final ConnectionUpstreamAliasEnum ID_TOKEN_HINT = new ConnectionUpstreamAliasEnum(Value.ID_TOKEN_HINT, "id_token_hint");

    public static final ConnectionUpstreamAliasEnum DISPLAY = new ConnectionUpstreamAliasEnum(Value.DISPLAY, "display");

    public static final ConnectionUpstreamAliasEnum MAX_AGE = new ConnectionUpstreamAliasEnum(Value.MAX_AGE, "max_age");

    public static final ConnectionUpstreamAliasEnum RESOURCE = new ConnectionUpstreamAliasEnum(Value.RESOURCE, "resource");

    public static final ConnectionUpstreamAliasEnum RESPONSE_MODE = new ConnectionUpstreamAliasEnum(Value.RESPONSE_MODE, "response_mode");

    public static final ConnectionUpstreamAliasEnum PROMPT = new ConnectionUpstreamAliasEnum(Value.PROMPT, "prompt");

    private final Value value;

    private final String string;

    ConnectionUpstreamAliasEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ConnectionUpstreamAliasEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        ACR_VALUES,
        AUDIENCE,
        CLIENT_ID,
        DISPLAY,
        ID_TOKEN_HINT,
        LOGIN_HINT,
        MAX_AGE,
        PROMPT,
        RESOURCE,
        RESPONSE_MODE,
        RESPONSE_TYPE,
        UI_LOCALES,
        UNKNOWN
    }

    public interface Visitor<T> {

        T visitAcrValues();

        T visitAudience();

        T visitClientId();

        T visitDisplay();

        T visitIdTokenHint();

        T visitLoginHint();

        T visitMaxAge();

        T visitPrompt();

        T visitResource();

        T visitResponseMode();

        T visitResponseType();

        T visitUiLocales();

        T visitUnknown(String unknownType);
    }
}
