/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ConnectionTypeEnumOidc {

    public static final ConnectionTypeEnumOidc FRONT_CHANNEL = new ConnectionTypeEnumOidc(Value.FRONT_CHANNEL, "front_channel");

    public static final ConnectionTypeEnumOidc BACK_CHANNEL = new ConnectionTypeEnumOidc(Value.BACK_CHANNEL, "back_channel");

    private final Value value;

    private final String string;

    ConnectionTypeEnumOidc(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ConnectionTypeEnumOidc valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        BACK_CHANNEL, FRONT_CHANNEL, UNKNOWN
    }

    public interface Visitor<T> {

        T visitBackChannel();

        T visitFrontChannel();

        T visitUnknown(String unknownType);
    }
}
