/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateConnectionRequestContentGoogleOAuth2.Builder.class)
public final class CreateConnectionRequestContentGoogleOAuth2 implements IConnectionPurposes, ICreateConnectionCommon {

    private final Optional<ConnectionAuthenticationPurpose> authentication;

    private final Optional<ConnectionConnectedAccountsPurpose> connectedAccounts;

    private final String name;

    private final Optional<List<String>> enabledClients;

    private final Optional<String> displayName;

    private final Optional<Boolean> isDomainConnection;

    private final Optional<Map<String, OptionalNullable<String>>> metadata;

    private final CreateConnectionRequestContentGoogleOAuth2Strategy strategy;

    private final Optional<ConnectionOptionsGoogleOAuth2> options;

    private final Map<String, Object> additionalProperties;

    private CreateConnectionRequestContentGoogleOAuth2(Optional<ConnectionAuthenticationPurpose> authentication, Optional<ConnectionConnectedAccountsPurpose> connectedAccounts, String name, Optional<List<String>> enabledClients, Optional<String> displayName, Optional<Boolean> isDomainConnection, Optional<Map<String, OptionalNullable<String>>> metadata, CreateConnectionRequestContentGoogleOAuth2Strategy strategy, Optional<ConnectionOptionsGoogleOAuth2> options, Map<String, Object> additionalProperties) {
        this.authentication = authentication;
        this.connectedAccounts = connectedAccounts;
        this.name = name;
        this.enabledClients = enabledClients;
        this.displayName = displayName;
        this.isDomainConnection = isDomainConnection;
        this.metadata = metadata;
        this.strategy = strategy;
        this.options = options;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("authentication")
    @java.lang.Override
    public Optional<ConnectionAuthenticationPurpose> getAuthentication() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("connected_accounts")
    @java.lang.Override
    public Optional<ConnectionConnectedAccountsPurpose> getConnectedAccounts() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("name")
    @java.lang.Override
    public String getName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Use of this property is NOT RECOMMENDED. Use the PATCH /v2/connections/{id}/clients endpoint to enable the connection for a set of clients.
     */
    @JsonProperty("enabled_clients")
    @java.lang.Override
    public Optional<List<String>> getEnabledClients() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("display_name")
    @java.lang.Override
    public Optional<String> getDisplayName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("is_domain_connection")
    @java.lang.Override
    public Optional<Boolean> getIsDomainConnection() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("metadata")
    @java.lang.Override
    public Optional<Map<String, OptionalNullable<String>>> getMetadata() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("strategy")
    public CreateConnectionRequestContentGoogleOAuth2Strategy getStrategy() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("options")
    public Optional<ConnectionOptionsGoogleOAuth2> getOptions() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateConnectionRequestContentGoogleOAuth2 other) {
        return authentication.equals(other.authentication) && connectedAccounts.equals(other.connectedAccounts) && name.equals(other.name) && enabledClients.equals(other.enabledClients) && displayName.equals(other.displayName) && isDomainConnection.equals(other.isDomainConnection) && metadata.equals(other.metadata) && strategy.equals(other.strategy) && options.equals(other.options);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static NameStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface NameStage {

        StrategyStage name(@NotNull String name);

        Builder from(CreateConnectionRequestContentGoogleOAuth2 other);
    }

    public interface StrategyStage {

        _FinalStage strategy(@NotNull CreateConnectionRequestContentGoogleOAuth2Strategy strategy);
    }

    public interface _FinalStage {

        CreateConnectionRequestContentGoogleOAuth2 build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage authentication(Optional<ConnectionAuthenticationPurpose> authentication);

        _FinalStage authentication(ConnectionAuthenticationPurpose authentication);

        _FinalStage connectedAccounts(Optional<ConnectionConnectedAccountsPurpose> connectedAccounts);

        _FinalStage connectedAccounts(ConnectionConnectedAccountsPurpose connectedAccounts);

        /**
         * <p>Use of this property is NOT RECOMMENDED. Use the PATCH /v2/connections/{id}/clients endpoint to enable the connection for a set of clients.</p>
         */
        _FinalStage enabledClients(Optional<List<String>> enabledClients);

        _FinalStage enabledClients(List<String> enabledClients);

        _FinalStage displayName(Optional<String> displayName);

        _FinalStage displayName(String displayName);

        _FinalStage isDomainConnection(Optional<Boolean> isDomainConnection);

        _FinalStage isDomainConnection(Boolean isDomainConnection);

        _FinalStage metadata(Optional<Map<String, OptionalNullable<String>>> metadata);

        _FinalStage metadata(Map<String, OptionalNullable<String>> metadata);

        _FinalStage options(Optional<ConnectionOptionsGoogleOAuth2> options);

        _FinalStage options(ConnectionOptionsGoogleOAuth2 options);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, StrategyStage, _FinalStage {

        private String name;

        private CreateConnectionRequestContentGoogleOAuth2Strategy strategy;

        private Optional<ConnectionOptionsGoogleOAuth2> options = Optional.empty();

        private Optional<Map<String, OptionalNullable<String>>> metadata = Optional.empty();

        private Optional<Boolean> isDomainConnection = Optional.empty();

        private Optional<String> displayName = Optional.empty();

        private Optional<List<String>> enabledClients = Optional.empty();

        private Optional<ConnectionConnectedAccountsPurpose> connectedAccounts = Optional.empty();

        private Optional<ConnectionAuthenticationPurpose> authentication = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(CreateConnectionRequestContentGoogleOAuth2 other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("name")
        public StrategyStage name(@NotNull String name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("strategy")
        public _FinalStage strategy(@NotNull CreateConnectionRequestContentGoogleOAuth2Strategy strategy) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage options(ConnectionOptionsGoogleOAuth2 options) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public _FinalStage options(Optional<ConnectionOptionsGoogleOAuth2> options) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage metadata(Map<String, OptionalNullable<String>> metadata) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<Map<String, OptionalNullable<String>>> metadata) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage isDomainConnection(Boolean isDomainConnection) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "is_domain_connection", nulls = Nulls.SKIP)
        public _FinalStage isDomainConnection(Optional<Boolean> isDomainConnection) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage displayName(String displayName) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "display_name", nulls = Nulls.SKIP)
        public _FinalStage displayName(Optional<String> displayName) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Use of this property is NOT RECOMMENDED. Use the PATCH /v2/connections/{id}/clients endpoint to enable the connection for a set of clients.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage enabledClients(List<String> enabledClients) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Use of this property is NOT RECOMMENDED. Use the PATCH /v2/connections/{id}/clients endpoint to enable the connection for a set of clients.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "enabled_clients", nulls = Nulls.SKIP)
        public _FinalStage enabledClients(Optional<List<String>> enabledClients) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage connectedAccounts(ConnectionConnectedAccountsPurpose connectedAccounts) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "connected_accounts", nulls = Nulls.SKIP)
        public _FinalStage connectedAccounts(Optional<ConnectionConnectedAccountsPurpose> connectedAccounts) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage authentication(ConnectionAuthenticationPurpose authentication) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "authentication", nulls = Nulls.SKIP)
        public _FinalStage authentication(Optional<ConnectionAuthenticationPurpose> authentication) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public CreateConnectionRequestContentGoogleOAuth2 build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
