/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateGuardianEnrollmentTicketResponseContent.Builder.class)
public final class CreateGuardianEnrollmentTicketResponseContent {

    private final Optional<String> ticketId;

    private final Optional<String> ticketUrl;

    private final Map<String, Object> additionalProperties;

    private CreateGuardianEnrollmentTicketResponseContent(Optional<String> ticketId, Optional<String> ticketUrl, Map<String, Object> additionalProperties) {
        this.ticketId = ticketId;
        this.ticketUrl = ticketUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The ticket_id used to identify the enrollment
     */
    @JsonProperty("ticket_id")
    public Optional<String> getTicketId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return The url you can use to start enrollment
     */
    @JsonProperty("ticket_url")
    public Optional<String> getTicketUrl() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateGuardianEnrollmentTicketResponseContent other) {
        return ticketId.equals(other.ticketId) && ticketUrl.equals(other.ticketUrl);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> ticketId = Optional.empty();

        private Optional<String> ticketUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(CreateGuardianEnrollmentTicketResponseContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The ticket_id used to identify the enrollment</p>
         */
        @JsonSetter(value = "ticket_id", nulls = Nulls.SKIP)
        public Builder ticketId(Optional<String> ticketId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder ticketId(String ticketId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The url you can use to start enrollment</p>
         */
        @JsonSetter(value = "ticket_url", nulls = Nulls.SKIP)
        public Builder ticketUrl(Optional<String> ticketUrl) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder ticketUrl(String ticketUrl) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public CreateGuardianEnrollmentTicketResponseContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
