/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = CreateLogStreamRequestContent.Deserializer.class)
public final class CreateLogStreamRequestContent {

    private final Object value;

    private final int type;

    private CreateLogStreamRequestContent(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateLogStreamRequestContent other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamHttpRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamEventBridgeRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamEventGridRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamDatadogRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamSplunkRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamSumoRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamSegmentRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CreateLogStreamRequestContent of(CreateLogStreamMixpanelRequestBody value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface Visitor<T> {

        T visit(CreateLogStreamHttpRequestBody value);

        T visit(CreateLogStreamEventBridgeRequestBody value);

        T visit(CreateLogStreamEventGridRequestBody value);

        T visit(CreateLogStreamDatadogRequestBody value);

        T visit(CreateLogStreamSplunkRequestBody value);

        T visit(CreateLogStreamSumoRequestBody value);

        T visit(CreateLogStreamSegmentRequestBody value);

        T visit(CreateLogStreamMixpanelRequestBody value);
    }

    static final class Deserializer extends StdDeserializer<CreateLogStreamRequestContent> {

        Deserializer() {
            super(CreateLogStreamRequestContent.class);
        }

        @java.lang.Override
        public CreateLogStreamRequestContent deserialize(JsonParser p, DeserializationContext context) throws IOException {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
