/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateFlowsVaultConnectionGoogleSheetsUninitialized.Builder.class)
public final class CreateFlowsVaultConnectionGoogleSheetsUninitialized {

    private final String name;

    private final FlowsVaultConnectionAppIdGoogleSheetsEnum appId;

    private final Map<String, Object> additionalProperties;

    private CreateFlowsVaultConnectionGoogleSheetsUninitialized(String name, FlowsVaultConnectionAppIdGoogleSheetsEnum appId, Map<String, Object> additionalProperties) {
        this.name = name;
        this.appId = appId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Flows Vault Connection name.
     */
    @JsonProperty("name")
    public String getName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("app_id")
    public FlowsVaultConnectionAppIdGoogleSheetsEnum getAppId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateFlowsVaultConnectionGoogleSheetsUninitialized other) {
        return name.equals(other.name) && appId.equals(other.appId);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static NameStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface NameStage {

        /**
         * <p>Flows Vault Connection name.</p>
         */
        AppIdStage name(@NotNull String name);

        Builder from(CreateFlowsVaultConnectionGoogleSheetsUninitialized other);
    }

    public interface AppIdStage {

        _FinalStage appId(@NotNull FlowsVaultConnectionAppIdGoogleSheetsEnum appId);
    }

    public interface _FinalStage {

        CreateFlowsVaultConnectionGoogleSheetsUninitialized build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, AppIdStage, _FinalStage {

        private String name;

        private FlowsVaultConnectionAppIdGoogleSheetsEnum appId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(CreateFlowsVaultConnectionGoogleSheetsUninitialized other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Flows Vault Connection name.</p>
         * <p>Flows Vault Connection name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public AppIdStage name(@NotNull String name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("app_id")
        public _FinalStage appId(@NotNull FlowsVaultConnectionAppIdGoogleSheetsEnum appId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public CreateFlowsVaultConnectionGoogleSheetsUninitialized build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
