/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateConnectionRequestContentOAuth1Strategy {

    public static final CreateConnectionRequestContentOAuth1Strategy OAUTH1 = new CreateConnectionRequestContentOAuth1Strategy(Value.OAUTH1, "oauth1");

    private final Value value;

    private final String string;

    CreateConnectionRequestContentOAuth1Strategy(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateConnectionRequestContentOAuth1Strategy valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        OAUTH1, UNKNOWN
    }

    public interface Visitor<T> {

        T visitOauth1();

        T visitUnknown(String unknownType);
    }
}
