/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateFlowsVaultConnectionJwtJwt.Builder.class)
public final class CreateFlowsVaultConnectionJwtJwt {

    private final String name;

    private final FlowsVaultConnectionAppIdJwtEnum appId;

    private final FlowsVaultConnectioSetupJwt setup;

    private final Map<String, Object> additionalProperties;

    private CreateFlowsVaultConnectionJwtJwt(String name, FlowsVaultConnectionAppIdJwtEnum appId, FlowsVaultConnectioSetupJwt setup, Map<String, Object> additionalProperties) {
        this.name = name;
        this.appId = appId;
        this.setup = setup;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Flows Vault Connection name.
     */
    @JsonProperty("name")
    public String getName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("app_id")
    public FlowsVaultConnectionAppIdJwtEnum getAppId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("setup")
    public FlowsVaultConnectioSetupJwt getSetup() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateFlowsVaultConnectionJwtJwt other) {
        return name.equals(other.name) && appId.equals(other.appId) && setup.equals(other.setup);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static NameStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface NameStage {

        /**
         * <p>Flows Vault Connection name.</p>
         */
        AppIdStage name(@NotNull String name);

        Builder from(CreateFlowsVaultConnectionJwtJwt other);
    }

    public interface AppIdStage {

        SetupStage appId(@NotNull FlowsVaultConnectionAppIdJwtEnum appId);
    }

    public interface SetupStage {

        _FinalStage setup(@NotNull FlowsVaultConnectioSetupJwt setup);
    }

    public interface _FinalStage {

        CreateFlowsVaultConnectionJwtJwt build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, AppIdStage, SetupStage, _FinalStage {

        private String name;

        private FlowsVaultConnectionAppIdJwtEnum appId;

        private FlowsVaultConnectioSetupJwt setup;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(CreateFlowsVaultConnectionJwtJwt other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Flows Vault Connection name.</p>
         * <p>Flows Vault Connection name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public AppIdStage name(@NotNull String name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("app_id")
        public SetupStage appId(@NotNull FlowsVaultConnectionAppIdJwtEnum appId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("setup")
        public _FinalStage setup(@NotNull FlowsVaultConnectioSetupJwt setup) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public CreateFlowsVaultConnectionJwtJwt build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
