/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateFlowsVaultConnectionMailchimpOauthCode.Builder.class)
public final class CreateFlowsVaultConnectionMailchimpOauthCode {

    private final String name;

    private final FlowsVaultConnectionAppIdMailchimpEnum appId;

    private final FlowsVaultConnectioSetupOauthCode setup;

    private final Map<String, Object> additionalProperties;

    private CreateFlowsVaultConnectionMailchimpOauthCode(String name, FlowsVaultConnectionAppIdMailchimpEnum appId, FlowsVaultConnectioSetupOauthCode setup, Map<String, Object> additionalProperties) {
        this.name = name;
        this.appId = appId;
        this.setup = setup;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Flows Vault Connection name.
     */
    @JsonProperty("name")
    public String getName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("app_id")
    public FlowsVaultConnectionAppIdMailchimpEnum getAppId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("setup")
    public FlowsVaultConnectioSetupOauthCode getSetup() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateFlowsVaultConnectionMailchimpOauthCode other) {
        return name.equals(other.name) && appId.equals(other.appId) && setup.equals(other.setup);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static NameStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface NameStage {

        /**
         * <p>Flows Vault Connection name.</p>
         */
        AppIdStage name(@NotNull String name);

        Builder from(CreateFlowsVaultConnectionMailchimpOauthCode other);
    }

    public interface AppIdStage {

        SetupStage appId(@NotNull FlowsVaultConnectionAppIdMailchimpEnum appId);
    }

    public interface SetupStage {

        _FinalStage setup(@NotNull FlowsVaultConnectioSetupOauthCode setup);
    }

    public interface _FinalStage {

        CreateFlowsVaultConnectionMailchimpOauthCode build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, AppIdStage, SetupStage, _FinalStage {

        private String name;

        private FlowsVaultConnectionAppIdMailchimpEnum appId;

        private FlowsVaultConnectioSetupOauthCode setup;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(CreateFlowsVaultConnectionMailchimpOauthCode other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Flows Vault Connection name.</p>
         * <p>Flows Vault Connection name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public AppIdStage name(@NotNull String name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("app_id")
        public SetupStage appId(@NotNull FlowsVaultConnectionAppIdMailchimpEnum appId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("setup")
        public _FinalStage setup(@NotNull FlowsVaultConnectioSetupOauthCode setup) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public CreateFlowsVaultConnectionMailchimpOauthCode build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
