/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.Nullable;
import com.auth0.client.mgmt.core.NullableNonemptyFilter;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateCustomDomainRequestContent.Builder.class)
public final class CreateCustomDomainRequestContent {

    private final String domain;

    private final CustomDomainProvisioningTypeEnum type;

    private final Optional<CustomDomainVerificationMethodEnum> verificationMethod;

    private final Optional<CustomDomainTlsPolicyEnum> tlsPolicy;

    private final OptionalNullable<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader;

    private final Optional<Map<String, OptionalNullable<String>>> domainMetadata;

    private final Optional<String> relyingPartyIdentifier;

    private final Map<String, Object> additionalProperties;

    private CreateCustomDomainRequestContent(String domain, CustomDomainProvisioningTypeEnum type, Optional<CustomDomainVerificationMethodEnum> verificationMethod, Optional<CustomDomainTlsPolicyEnum> tlsPolicy, OptionalNullable<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader, Optional<Map<String, OptionalNullable<String>>> domainMetadata, Optional<String> relyingPartyIdentifier, Map<String, Object> additionalProperties) {
        this.domain = domain;
        this.type = type;
        this.verificationMethod = verificationMethod;
        this.tlsPolicy = tlsPolicy;
        this.customClientIpHeader = customClientIpHeader;
        this.domainMetadata = domainMetadata;
        this.relyingPartyIdentifier = relyingPartyIdentifier;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Domain name.
     */
    @JsonProperty("domain")
    public String getDomain() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("type")
    public CustomDomainProvisioningTypeEnum getType() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("verification_method")
    public Optional<CustomDomainVerificationMethodEnum> getVerificationMethod() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("tls_policy")
    public Optional<CustomDomainTlsPolicyEnum> getTlsPolicy() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("custom_client_ip_header")
    public OptionalNullable<CustomDomainCustomClientIpHeaderEnum> getCustomClientIpHeader() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("domain_metadata")
    public Optional<Map<String, OptionalNullable<String>>> getDomainMetadata() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Relying Party ID (rpId) to be used for Passkeys on this custom domain. If not provided, the full domain will be used.
     */
    @JsonProperty("relying_party_identifier")
    public Optional<String> getRelyingPartyIdentifier() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateCustomDomainRequestContent other) {
        return domain.equals(other.domain) && type.equals(other.type) && verificationMethod.equals(other.verificationMethod) && tlsPolicy.equals(other.tlsPolicy) && customClientIpHeader.equals(other.customClientIpHeader) && domainMetadata.equals(other.domainMetadata) && relyingPartyIdentifier.equals(other.relyingPartyIdentifier);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static DomainStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface DomainStage {

        /**
         * <p>Domain name.</p>
         */
        TypeStage domain(@NotNull String domain);

        Builder from(CreateCustomDomainRequestContent other);
    }

    public interface TypeStage {

        _FinalStage type(@NotNull CustomDomainProvisioningTypeEnum type);
    }

    public interface _FinalStage {

        CreateCustomDomainRequestContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage verificationMethod(Optional<CustomDomainVerificationMethodEnum> verificationMethod);

        _FinalStage verificationMethod(CustomDomainVerificationMethodEnum verificationMethod);

        _FinalStage tlsPolicy(Optional<CustomDomainTlsPolicyEnum> tlsPolicy);

        _FinalStage tlsPolicy(CustomDomainTlsPolicyEnum tlsPolicy);

        _FinalStage customClientIpHeader(OptionalNullable<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader);

        _FinalStage customClientIpHeader(CustomDomainCustomClientIpHeaderEnum customClientIpHeader);

        _FinalStage customClientIpHeader(Optional<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader);

        _FinalStage customClientIpHeader(Nullable<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader);

        _FinalStage domainMetadata(Optional<Map<String, OptionalNullable<String>>> domainMetadata);

        _FinalStage domainMetadata(Map<String, OptionalNullable<String>> domainMetadata);

        /**
         * <p>Relying Party ID (rpId) to be used for Passkeys on this custom domain. If not provided, the full domain will be used.</p>
         */
        _FinalStage relyingPartyIdentifier(Optional<String> relyingPartyIdentifier);

        _FinalStage relyingPartyIdentifier(String relyingPartyIdentifier);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DomainStage, TypeStage, _FinalStage {

        private String domain;

        private CustomDomainProvisioningTypeEnum type;

        private Optional<String> relyingPartyIdentifier = Optional.empty();

        private Optional<Map<String, OptionalNullable<String>>> domainMetadata = Optional.empty();

        private OptionalNullable<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader = OptionalNullable.absent();

        private Optional<CustomDomainTlsPolicyEnum> tlsPolicy = Optional.empty();

        private Optional<CustomDomainVerificationMethodEnum> verificationMethod = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(CreateCustomDomainRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Domain name.</p>
         * <p>Domain name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("domain")
        public TypeStage domain(@NotNull String domain) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull CustomDomainProvisioningTypeEnum type) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Relying Party ID (rpId) to be used for Passkeys on this custom domain. If not provided, the full domain will be used.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage relyingPartyIdentifier(String relyingPartyIdentifier) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Relying Party ID (rpId) to be used for Passkeys on this custom domain. If not provided, the full domain will be used.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "relying_party_identifier", nulls = Nulls.SKIP)
        public _FinalStage relyingPartyIdentifier(Optional<String> relyingPartyIdentifier) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage domainMetadata(Map<String, OptionalNullable<String>> domainMetadata) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "domain_metadata", nulls = Nulls.SKIP)
        public _FinalStage domainMetadata(Optional<Map<String, OptionalNullable<String>>> domainMetadata) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage customClientIpHeader(Nullable<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage customClientIpHeader(Optional<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage customClientIpHeader(CustomDomainCustomClientIpHeaderEnum customClientIpHeader) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "custom_client_ip_header", nulls = Nulls.SKIP)
        public _FinalStage customClientIpHeader(OptionalNullable<CustomDomainCustomClientIpHeaderEnum> customClientIpHeader) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage tlsPolicy(CustomDomainTlsPolicyEnum tlsPolicy) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "tls_policy", nulls = Nulls.SKIP)
        public _FinalStage tlsPolicy(Optional<CustomDomainTlsPolicyEnum> tlsPolicy) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage verificationMethod(CustomDomainVerificationMethodEnum verificationMethod) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "verification_method", nulls = Nulls.SKIP)
        public _FinalStage verificationMethod(Optional<CustomDomainVerificationMethodEnum> verificationMethod) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public CreateCustomDomainRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
