/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateUserAttributeProfileRequestContent.Builder.class)
public final class CreateUserAttributeProfileRequestContent {

    private final String name;

    private final Optional<UserAttributeProfileUserId> userId;

    private final Map<String, UserAttributeProfileUserAttributeAdditionalProperties> userAttributes;

    private final Map<String, Object> additionalProperties;

    private CreateUserAttributeProfileRequestContent(String name, Optional<UserAttributeProfileUserId> userId, Map<String, UserAttributeProfileUserAttributeAdditionalProperties> userAttributes, Map<String, Object> additionalProperties) {
        this.name = name;
        this.userId = userId;
        this.userAttributes = userAttributes;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("name")
    public String getName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("user_id")
    public Optional<UserAttributeProfileUserId> getUserId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("user_attributes")
    public Map<String, UserAttributeProfileUserAttributeAdditionalProperties> getUserAttributes() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(CreateUserAttributeProfileRequestContent other) {
        return name.equals(other.name) && userId.equals(other.userId) && userAttributes.equals(other.userAttributes);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static NameStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface NameStage {

        _FinalStage name(@NotNull String name);

        Builder from(CreateUserAttributeProfileRequestContent other);
    }

    public interface _FinalStage {

        CreateUserAttributeProfileRequestContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage userId(Optional<UserAttributeProfileUserId> userId);

        _FinalStage userId(UserAttributeProfileUserId userId);

        _FinalStage userAttributes(Map<String, UserAttributeProfileUserAttributeAdditionalProperties> userAttributes);

        _FinalStage putAllUserAttributes(Map<String, UserAttributeProfileUserAttributeAdditionalProperties> userAttributes);

        _FinalStage userAttributes(String key, UserAttributeProfileUserAttributeAdditionalProperties value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {

        private String name;

        private Map<String, UserAttributeProfileUserAttributeAdditionalProperties> userAttributes = new LinkedHashMap<>();

        private Optional<UserAttributeProfileUserId> userId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(CreateUserAttributeProfileRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage userAttributes(String key, UserAttributeProfileUserAttributeAdditionalProperties value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage putAllUserAttributes(Map<String, UserAttributeProfileUserAttributeAdditionalProperties> userAttributes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "user_attributes", nulls = Nulls.SKIP)
        public _FinalStage userAttributes(Map<String, UserAttributeProfileUserAttributeAdditionalProperties> userAttributes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage userId(UserAttributeProfileUserId userId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<UserAttributeProfileUserId> userId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public CreateUserAttributeProfileRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
