/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailProviderCredentialsSchemaClientId.Builder.class)
public final class EmailProviderCredentialsSchemaClientId {

    private final Optional<String> tenantId;

    private final Optional<String> clientId;

    private final Optional<String> clientSecret;

    private final Map<String, Object> additionalProperties;

    private EmailProviderCredentialsSchemaClientId(Optional<String> tenantId, Optional<String> clientId, Optional<String> clientSecret, Map<String, Object> additionalProperties) {
        this.tenantId = tenantId;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Microsoft 365 Tenant ID.
     */
    @JsonProperty("tenantId")
    public Optional<String> getTenantId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Microsoft 365 Client ID.
     */
    @JsonProperty("clientId")
    public Optional<String> getClientId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Microsoft 365 Client Secret.
     */
    @JsonProperty("clientSecret")
    public Optional<String> getClientSecret() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(EmailProviderCredentialsSchemaClientId other) {
        return tenantId.equals(other.tenantId) && clientId.equals(other.clientId) && clientSecret.equals(other.clientSecret);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> tenantId = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<String> clientSecret = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(EmailProviderCredentialsSchemaClientId other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Microsoft 365 Tenant ID.</p>
         */
        @JsonSetter(value = "tenantId", nulls = Nulls.SKIP)
        public Builder tenantId(Optional<String> tenantId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder tenantId(String tenantId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Microsoft 365 Client ID.</p>
         */
        @JsonSetter(value = "clientId", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder clientId(String clientId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Microsoft 365 Client Secret.</p>
         */
        @JsonSetter(value = "clientSecret", nulls = Nulls.SKIP)
        public Builder clientSecret(Optional<String> clientSecret) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder clientSecret(String clientSecret) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public EmailProviderCredentialsSchemaClientId build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
