/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EmailTemplateNameEnum {

    public static final EmailTemplateNameEnum CHANGE_PASSWORD = new EmailTemplateNameEnum(Value.CHANGE_PASSWORD, "change_password");

    public static final EmailTemplateNameEnum RESET_EMAIL_BY_CODE = new EmailTemplateNameEnum(Value.RESET_EMAIL_BY_CODE, "reset_email_by_code");

    public static final EmailTemplateNameEnum STOLEN_CREDENTIALS = new EmailTemplateNameEnum(Value.STOLEN_CREDENTIALS, "stolen_credentials");

    public static final EmailTemplateNameEnum USER_INVITATION = new EmailTemplateNameEnum(Value.USER_INVITATION, "user_invitation");

    public static final EmailTemplateNameEnum BLOCKED_ACCOUNT = new EmailTemplateNameEnum(Value.BLOCKED_ACCOUNT, "blocked_account");

    public static final EmailTemplateNameEnum ENROLLMENT_EMAIL = new EmailTemplateNameEnum(Value.ENROLLMENT_EMAIL, "enrollment_email");

    public static final EmailTemplateNameEnum PASSWORD_RESET = new EmailTemplateNameEnum(Value.PASSWORD_RESET, "password_reset");

    public static final EmailTemplateNameEnum WELCOME_EMAIL = new EmailTemplateNameEnum(Value.WELCOME_EMAIL, "welcome_email");

    public static final EmailTemplateNameEnum VERIFY_EMAIL_BY_CODE = new EmailTemplateNameEnum(Value.VERIFY_EMAIL_BY_CODE, "verify_email_by_code");

    public static final EmailTemplateNameEnum VERIFY_EMAIL = new EmailTemplateNameEnum(Value.VERIFY_EMAIL, "verify_email");

    public static final EmailTemplateNameEnum MFA_OOB_CODE = new EmailTemplateNameEnum(Value.MFA_OOB_CODE, "mfa_oob_code");

    public static final EmailTemplateNameEnum RESET_EMAIL = new EmailTemplateNameEnum(Value.RESET_EMAIL, "reset_email");

    public static final EmailTemplateNameEnum ASYNC_APPROVAL = new EmailTemplateNameEnum(Value.ASYNC_APPROVAL, "async_approval");

    private final Value value;

    private final String string;

    EmailTemplateNameEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EmailTemplateNameEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        VERIFY_EMAIL,
        VERIFY_EMAIL_BY_CODE,
        RESET_EMAIL,
        RESET_EMAIL_BY_CODE,
        WELCOME_EMAIL,
        BLOCKED_ACCOUNT,
        STOLEN_CREDENTIALS,
        ENROLLMENT_EMAIL,
        MFA_OOB_CODE,
        USER_INVITATION,
        CHANGE_PASSWORD,
        PASSWORD_RESET,
        ASYNC_APPROVAL,
        UNKNOWN
    }

    public interface Visitor<T> {

        T visitVerifyEmail();

        T visitVerifyEmailByCode();

        T visitResetEmail();

        T visitResetEmailByCode();

        T visitWelcomeEmail();

        T visitBlockedAccount();

        T visitStolenCredentials();

        T visitEnrollmentEmail();

        T visitMfaOobCode();

        T visitUserInvitation();

        T visitChangePassword();

        T visitPasswordReset();

        T visitAsyncApproval();

        T visitUnknown(String unknownType);
    }
}
