/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EnabledFeaturesEnum {

    public static final EnabledFeaturesEnum SCIM = new EnabledFeaturesEnum(Value.SCIM, "scim");

    public static final EnabledFeaturesEnum UNIVERSAL_LOGOUT = new EnabledFeaturesEnum(Value.UNIVERSAL_LOGOUT, "universal_logout");

    private final Value value;

    private final String string;

    EnabledFeaturesEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EnabledFeaturesEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        SCIM, UNIVERSAL_LOGOUT, UNKNOWN
    }

    public interface Visitor<T> {

        T visitScim();

        T visitUniversalLogout();

        T visitUnknown(String unknownType);
    }
}
