/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventUserUpdated.Builder.class)
public final class EventStreamCloudEventUserUpdated {

    private final String offset;

    private final EventStreamCloudEventUserUpdatedCloudEvent event;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventUserUpdated(String offset, EventStreamCloudEventUserUpdatedCloudEvent event, Map<String, Object> additionalProperties) {
        this.offset = offset;
        this.event = event;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Opaque cursor representing position in the stream. Pass as the <code>from</code> query parameter to resume.
     */
    @JsonProperty("offset")
    public String getOffset() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("event")
    public EventStreamCloudEventUserUpdatedCloudEvent getEvent() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(EventStreamCloudEventUserUpdated other) {
        return offset.equals(other.offset) && event.equals(other.event);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static OffsetStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface OffsetStage {

        /**
         * <p>Opaque cursor representing position in the stream. Pass as the <code>from</code> query parameter to resume.</p>
         */
        EventStage offset(@NotNull String offset);

        Builder from(EventStreamCloudEventUserUpdated other);
    }

    public interface EventStage {

        _FinalStage event(@NotNull EventStreamCloudEventUserUpdatedCloudEvent event);
    }

    public interface _FinalStage {

        EventStreamCloudEventUserUpdated build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OffsetStage, EventStage, _FinalStage {

        private String offset;

        private EventStreamCloudEventUserUpdatedCloudEvent event;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(EventStreamCloudEventUserUpdated other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Opaque cursor representing position in the stream. Pass as the <code>from</code> query parameter to resume.</p>
         * <p>Opaque cursor representing position in the stream. Pass as the <code>from</code> query parameter to resume.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("offset")
        public EventStage offset(@NotNull String offset) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("event")
        public _FinalStage event(@NotNull EventStreamCloudEventUserUpdatedCloudEvent event) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public EventStreamCloudEventUserUpdated build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
