/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventGroupMemberDeletedObject.Builder.class)
public final class EventStreamCloudEventGroupMemberDeletedObject {

    private final EventStreamCloudEventGroupMemberDeletedObjectGroup group;

    private final EventStreamCloudEventGroupMemberDeletedObjectMember member;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventGroupMemberDeletedObject(EventStreamCloudEventGroupMemberDeletedObjectGroup group, EventStreamCloudEventGroupMemberDeletedObjectMember member, Map<String, Object> additionalProperties) {
        this.group = group;
        this.member = member;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("group")
    public EventStreamCloudEventGroupMemberDeletedObjectGroup getGroup() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("member")
    public EventStreamCloudEventGroupMemberDeletedObjectMember getMember() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(EventStreamCloudEventGroupMemberDeletedObject other) {
        return group.equals(other.group) && member.equals(other.member);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static GroupStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface GroupStage {

        MemberStage group(@NotNull EventStreamCloudEventGroupMemberDeletedObjectGroup group);

        Builder from(EventStreamCloudEventGroupMemberDeletedObject other);
    }

    public interface MemberStage {

        _FinalStage member(@NotNull EventStreamCloudEventGroupMemberDeletedObjectMember member);
    }

    public interface _FinalStage {

        EventStreamCloudEventGroupMemberDeletedObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements GroupStage, MemberStage, _FinalStage {

        private EventStreamCloudEventGroupMemberDeletedObjectGroup group;

        private EventStreamCloudEventGroupMemberDeletedObjectMember member;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(EventStreamCloudEventGroupMemberDeletedObject other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("group")
        public MemberStage group(@NotNull EventStreamCloudEventGroupMemberDeletedObjectGroup group) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("member")
        public _FinalStage member(@NotNull EventStreamCloudEventGroupMemberDeletedObjectMember member) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public EventStreamCloudEventGroupMemberDeletedObject build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
