/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventErrorDetail.Builder.class)
public final class EventStreamCloudEventErrorDetail {

    private final EventStreamCloudEventErrorCodeEnum code;

    private final String message;

    private final Optional<String> offset;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventErrorDetail(EventStreamCloudEventErrorCodeEnum code, String message, Optional<String> offset, Map<String, Object> additionalProperties) {
        this.code = code;
        this.message = message;
        this.offset = offset;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("code")
    public EventStreamCloudEventErrorCodeEnum getCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Human-readable error message.
     */
    @JsonProperty("message")
    public String getMessage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return The cursor at the time of the error (when available). Can be used to resume from this position.
     */
    @JsonProperty("offset")
    public Optional<String> getOffset() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(EventStreamCloudEventErrorDetail other) {
        return code.equals(other.code) && message.equals(other.message) && offset.equals(other.offset);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static CodeStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface CodeStage {

        MessageStage code(@NotNull EventStreamCloudEventErrorCodeEnum code);

        Builder from(EventStreamCloudEventErrorDetail other);
    }

    public interface MessageStage {

        /**
         * <p>Human-readable error message.</p>
         */
        _FinalStage message(@NotNull String message);
    }

    public interface _FinalStage {

        EventStreamCloudEventErrorDetail build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The cursor at the time of the error (when available). Can be used to resume from this position.</p>
         */
        _FinalStage offset(Optional<String> offset);

        _FinalStage offset(String offset);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CodeStage, MessageStage, _FinalStage {

        private EventStreamCloudEventErrorCodeEnum code;

        private String message;

        private Optional<String> offset = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(EventStreamCloudEventErrorDetail other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("code")
        public MessageStage code(@NotNull EventStreamCloudEventErrorCodeEnum code) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Human-readable error message.</p>
         * <p>Human-readable error message.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The cursor at the time of the error (when available). Can be used to resume from this position.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage offset(String offset) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The cursor at the time of the error (when available). Can be used to resume from this position.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public _FinalStage offset(Optional<String> offset) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public EventStreamCloudEventErrorDetail build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
