/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EventStreamCloudEventUserUpdatedObjectIdentitiesItemPasswordlessProviderEnum {

    public static final EventStreamCloudEventUserUpdatedObjectIdentitiesItemPasswordlessProviderEnum EMAIL = new EventStreamCloudEventUserUpdatedObjectIdentitiesItemPasswordlessProviderEnum(Value.EMAIL, "email");

    public static final EventStreamCloudEventUserUpdatedObjectIdentitiesItemPasswordlessProviderEnum SMS = new EventStreamCloudEventUserUpdatedObjectIdentitiesItemPasswordlessProviderEnum(Value.SMS, "sms");

    private final Value value;

    private final String string;

    EventStreamCloudEventUserUpdatedObjectIdentitiesItemPasswordlessProviderEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EventStreamCloudEventUserUpdatedObjectIdentitiesItemPasswordlessProviderEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        EMAIL, SMS, UNKNOWN
    }

    public interface Visitor<T> {

        T visitEmail();

        T visitSms();

        T visitUnknown(String unknownType);
    }
}
