/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventUserUpdatedData.Builder.class)
public final class EventStreamCloudEventUserUpdatedData {

    private final EventStreamCloudEventUserUpdatedObject object;

    private final Optional<EventStreamCloudEventContext> context;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventUserUpdatedData(EventStreamCloudEventUserUpdatedObject object, Optional<EventStreamCloudEventContext> context, Map<String, Object> additionalProperties) {
        this.object = object;
        this.context = context;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public EventStreamCloudEventUserUpdatedObject getObject() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("context")
    public Optional<EventStreamCloudEventContext> getContext() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(EventStreamCloudEventUserUpdatedData other) {
        return object.equals(other.object) && context.equals(other.context);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static ObjectStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface ObjectStage {

        _FinalStage object(@NotNull EventStreamCloudEventUserUpdatedObject object);

        Builder from(EventStreamCloudEventUserUpdatedData other);
    }

    public interface _FinalStage {

        EventStreamCloudEventUserUpdatedData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage context(Optional<EventStreamCloudEventContext> context);

        _FinalStage context(EventStreamCloudEventContext context);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ObjectStage, _FinalStage {

        private EventStreamCloudEventUserUpdatedObject object;

        private Optional<EventStreamCloudEventContext> context = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(EventStreamCloudEventUserUpdatedData other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("object")
        public _FinalStage object(@NotNull EventStreamCloudEventUserUpdatedObject object) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage context(EventStreamCloudEventContext context) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "context", nulls = Nulls.SKIP)
        public _FinalStage context(Optional<EventStreamCloudEventContext> context) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public EventStreamCloudEventUserUpdatedData build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
