/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventOrgMemberAddedObject.Builder.class)
public final class EventStreamCloudEventOrgMemberAddedObject {

    private final EventStreamCloudEventOrgMemberAddedObjectOrganization organization;

    private final EventStreamCloudEventOrgMemberAddedObjectUser user;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventOrgMemberAddedObject(EventStreamCloudEventOrgMemberAddedObjectOrganization organization, EventStreamCloudEventOrgMemberAddedObjectUser user, Map<String, Object> additionalProperties) {
        this.organization = organization;
        this.user = user;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("organization")
    public EventStreamCloudEventOrgMemberAddedObjectOrganization getOrganization() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("user")
    public EventStreamCloudEventOrgMemberAddedObjectUser getUser() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(EventStreamCloudEventOrgMemberAddedObject other) {
        return organization.equals(other.organization) && user.equals(other.user);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static OrganizationStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface OrganizationStage {

        UserStage organization(@NotNull EventStreamCloudEventOrgMemberAddedObjectOrganization organization);

        Builder from(EventStreamCloudEventOrgMemberAddedObject other);
    }

    public interface UserStage {

        _FinalStage user(@NotNull EventStreamCloudEventOrgMemberAddedObjectUser user);
    }

    public interface _FinalStage {

        EventStreamCloudEventOrgMemberAddedObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OrganizationStage, UserStage, _FinalStage {

        private EventStreamCloudEventOrgMemberAddedObjectOrganization organization;

        private EventStreamCloudEventOrgMemberAddedObjectUser user;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(EventStreamCloudEventOrgMemberAddedObject other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("organization")
        public UserStage organization(@NotNull EventStreamCloudEventOrgMemberAddedObjectOrganization organization) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("user")
        public _FinalStage user(@NotNull EventStreamCloudEventOrgMemberAddedObjectUser user) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public EventStreamCloudEventOrgMemberAddedObject build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
