/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamEventBridgeConfiguration.Builder.class)
public final class EventStreamEventBridgeConfiguration {

    private final String awsAccountId;

    private final EventStreamEventBridgeAwsRegionEnum awsRegion;

    private final Optional<String> awsPartnerEventSource;

    private final Map<String, Object> additionalProperties;

    private EventStreamEventBridgeConfiguration(String awsAccountId, EventStreamEventBridgeAwsRegionEnum awsRegion, Optional<String> awsPartnerEventSource, Map<String, Object> additionalProperties) {
        this.awsAccountId = awsAccountId;
        this.awsRegion = awsRegion;
        this.awsPartnerEventSource = awsPartnerEventSource;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return AWS Account ID for EventBridge destination.
     */
    @JsonProperty("aws_account_id")
    public String getAwsAccountId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("aws_region")
    public EventStreamEventBridgeAwsRegionEnum getAwsRegion() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return AWS Partner Event Source for EventBridge destination.
     */
    @JsonProperty("aws_partner_event_source")
    public Optional<String> getAwsPartnerEventSource() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(EventStreamEventBridgeConfiguration other) {
        return awsAccountId.equals(other.awsAccountId) && awsRegion.equals(other.awsRegion) && awsPartnerEventSource.equals(other.awsPartnerEventSource);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static AwsAccountIdStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface AwsAccountIdStage {

        /**
         * <p>AWS Account ID for EventBridge destination.</p>
         */
        AwsRegionStage awsAccountId(@NotNull String awsAccountId);

        Builder from(EventStreamEventBridgeConfiguration other);
    }

    public interface AwsRegionStage {

        _FinalStage awsRegion(@NotNull EventStreamEventBridgeAwsRegionEnum awsRegion);
    }

    public interface _FinalStage {

        EventStreamEventBridgeConfiguration build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>AWS Partner Event Source for EventBridge destination.</p>
         */
        _FinalStage awsPartnerEventSource(Optional<String> awsPartnerEventSource);

        _FinalStage awsPartnerEventSource(String awsPartnerEventSource);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AwsAccountIdStage, AwsRegionStage, _FinalStage {

        private String awsAccountId;

        private EventStreamEventBridgeAwsRegionEnum awsRegion;

        private Optional<String> awsPartnerEventSource = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(EventStreamEventBridgeConfiguration other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>AWS Account ID for EventBridge destination.</p>
         * <p>AWS Account ID for EventBridge destination.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("aws_account_id")
        public AwsRegionStage awsAccountId(@NotNull String awsAccountId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("aws_region")
        public _FinalStage awsRegion(@NotNull EventStreamEventBridgeAwsRegionEnum awsRegion) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>AWS Partner Event Source for EventBridge destination.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage awsPartnerEventSource(String awsPartnerEventSource) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>AWS Partner Event Source for EventBridge destination.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "aws_partner_event_source", nulls = Nulls.SKIP)
        public _FinalStage awsPartnerEventSource(Optional<String> awsPartnerEventSource) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public EventStreamEventBridgeConfiguration build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
