/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowActionHttpSendRequestParamsBasicAuth.Builder.class)
public final class FlowActionHttpSendRequestParamsBasicAuth {

    private final Optional<String> username;

    private final Optional<String> password;

    private final Map<String, Object> additionalProperties;

    private FlowActionHttpSendRequestParamsBasicAuth(Optional<String> username, Optional<String> password, Map<String, Object> additionalProperties) {
        this.username = username;
        this.password = password;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("username")
    public Optional<String> getUsername() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("password")
    public Optional<String> getPassword() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FlowActionHttpSendRequestParamsBasicAuth other) {
        return username.equals(other.username) && password.equals(other.password);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> username = Optional.empty();

        private Optional<String> password = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(FlowActionHttpSendRequestParamsBasicAuth other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "username", nulls = Nulls.SKIP)
        public Builder username(Optional<String> username) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder username(String username) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "password", nulls = Nulls.SKIP)
        public Builder password(Optional<String> password) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder password(String password) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public FlowActionHttpSendRequestParamsBasicAuth build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
