/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowActionOtpVerifyCodeParams.Builder.class)
public final class FlowActionOtpVerifyCodeParams {

    private final String reference;

    private final FlowActionOtpVerifyCodeParamsCode code;

    private final Map<String, Object> additionalProperties;

    private FlowActionOtpVerifyCodeParams(String reference, FlowActionOtpVerifyCodeParamsCode code, Map<String, Object> additionalProperties) {
        this.reference = reference;
        this.code = code;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("reference")
    public String getReference() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("code")
    public FlowActionOtpVerifyCodeParamsCode getCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FlowActionOtpVerifyCodeParams other) {
        return reference.equals(other.reference) && code.equals(other.code);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static ReferenceStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface ReferenceStage {

        CodeStage reference(@NotNull String reference);

        Builder from(FlowActionOtpVerifyCodeParams other);
    }

    public interface CodeStage {

        _FinalStage code(@NotNull FlowActionOtpVerifyCodeParamsCode code);
    }

    public interface _FinalStage {

        FlowActionOtpVerifyCodeParams build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReferenceStage, CodeStage, _FinalStage {

        private String reference;

        private FlowActionOtpVerifyCodeParamsCode code;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(FlowActionOtpVerifyCodeParams other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("reference")
        public CodeStage reference(@NotNull String reference) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("code")
        public _FinalStage code(@NotNull FlowActionOtpVerifyCodeParamsCode code) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public FlowActionOtpVerifyCodeParams build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
