/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowActionEmailVerifyEmailParamsRules.Builder.class)
public final class FlowActionEmailVerifyEmailParamsRules {

    private final Optional<Boolean> requireMxRecord;

    private final Optional<Boolean> blockAliases;

    private final Optional<Boolean> blockFreeEmails;

    private final Optional<Boolean> blockDisposableEmails;

    private final Optional<List<String>> blocklist;

    private final Optional<List<String>> allowlist;

    private final Map<String, Object> additionalProperties;

    private FlowActionEmailVerifyEmailParamsRules(Optional<Boolean> requireMxRecord, Optional<Boolean> blockAliases, Optional<Boolean> blockFreeEmails, Optional<Boolean> blockDisposableEmails, Optional<List<String>> blocklist, Optional<List<String>> allowlist, Map<String, Object> additionalProperties) {
        this.requireMxRecord = requireMxRecord;
        this.blockAliases = blockAliases;
        this.blockFreeEmails = blockFreeEmails;
        this.blockDisposableEmails = blockDisposableEmails;
        this.blocklist = blocklist;
        this.allowlist = allowlist;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("require_mx_record")
    public Optional<Boolean> getRequireMxRecord() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("block_aliases")
    public Optional<Boolean> getBlockAliases() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("block_free_emails")
    public Optional<Boolean> getBlockFreeEmails() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("block_disposable_emails")
    public Optional<Boolean> getBlockDisposableEmails() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("blocklist")
    public Optional<List<String>> getBlocklist() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("allowlist")
    public Optional<List<String>> getAllowlist() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FlowActionEmailVerifyEmailParamsRules other) {
        return requireMxRecord.equals(other.requireMxRecord) && blockAliases.equals(other.blockAliases) && blockFreeEmails.equals(other.blockFreeEmails) && blockDisposableEmails.equals(other.blockDisposableEmails) && blocklist.equals(other.blocklist) && allowlist.equals(other.allowlist);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<Boolean> requireMxRecord = Optional.empty();

        private Optional<Boolean> blockAliases = Optional.empty();

        private Optional<Boolean> blockFreeEmails = Optional.empty();

        private Optional<Boolean> blockDisposableEmails = Optional.empty();

        private Optional<List<String>> blocklist = Optional.empty();

        private Optional<List<String>> allowlist = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(FlowActionEmailVerifyEmailParamsRules other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "require_mx_record", nulls = Nulls.SKIP)
        public Builder requireMxRecord(Optional<Boolean> requireMxRecord) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder requireMxRecord(Boolean requireMxRecord) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "block_aliases", nulls = Nulls.SKIP)
        public Builder blockAliases(Optional<Boolean> blockAliases) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder blockAliases(Boolean blockAliases) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "block_free_emails", nulls = Nulls.SKIP)
        public Builder blockFreeEmails(Optional<Boolean> blockFreeEmails) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder blockFreeEmails(Boolean blockFreeEmails) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "block_disposable_emails", nulls = Nulls.SKIP)
        public Builder blockDisposableEmails(Optional<Boolean> blockDisposableEmails) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder blockDisposableEmails(Boolean blockDisposableEmails) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "blocklist", nulls = Nulls.SKIP)
        public Builder blocklist(Optional<List<String>> blocklist) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder blocklist(List<String> blocklist) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "allowlist", nulls = Nulls.SKIP)
        public Builder allowlist(Optional<List<String>> allowlist) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder allowlist(List<String> allowlist) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public FlowActionEmailVerifyEmailParamsRules build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
