/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowActionSalesforceSearchLeadsParams.Builder.class)
public final class FlowActionSalesforceSearchLeadsParams {

    private final String connectionId;

    private final FlowActionSalesforceSearchLeadsParamsSearchField searchField;

    private final String searchValue;

    private final List<String> leadFields;

    private final Map<String, Object> additionalProperties;

    private FlowActionSalesforceSearchLeadsParams(String connectionId, FlowActionSalesforceSearchLeadsParamsSearchField searchField, String searchValue, List<String> leadFields, Map<String, Object> additionalProperties) {
        this.connectionId = connectionId;
        this.searchField = searchField;
        this.searchValue = searchValue;
        this.leadFields = leadFields;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("connection_id")
    public String getConnectionId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("search_field")
    public FlowActionSalesforceSearchLeadsParamsSearchField getSearchField() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("search_value")
    public String getSearchValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("lead_fields")
    public List<String> getLeadFields() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FlowActionSalesforceSearchLeadsParams other) {
        return connectionId.equals(other.connectionId) && searchField.equals(other.searchField) && searchValue.equals(other.searchValue) && leadFields.equals(other.leadFields);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static ConnectionIdStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface ConnectionIdStage {

        SearchFieldStage connectionId(@NotNull String connectionId);

        Builder from(FlowActionSalesforceSearchLeadsParams other);
    }

    public interface SearchFieldStage {

        SearchValueStage searchField(@NotNull FlowActionSalesforceSearchLeadsParamsSearchField searchField);
    }

    public interface SearchValueStage {

        _FinalStage searchValue(@NotNull String searchValue);
    }

    public interface _FinalStage {

        FlowActionSalesforceSearchLeadsParams build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage leadFields(List<String> leadFields);

        _FinalStage addLeadFields(String leadFields);

        _FinalStage addAllLeadFields(List<String> leadFields);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ConnectionIdStage, SearchFieldStage, SearchValueStage, _FinalStage {

        private String connectionId;

        private FlowActionSalesforceSearchLeadsParamsSearchField searchField;

        private String searchValue;

        private List<String> leadFields = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(FlowActionSalesforceSearchLeadsParams other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("connection_id")
        public SearchFieldStage connectionId(@NotNull String connectionId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("search_field")
        public SearchValueStage searchField(@NotNull FlowActionSalesforceSearchLeadsParamsSearchField searchField) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("search_value")
        public _FinalStage searchValue(@NotNull String searchValue) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage addAllLeadFields(List<String> leadFields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage addLeadFields(String leadFields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "lead_fields", nulls = Nulls.SKIP)
        public _FinalStage leadFields(List<String> leadFields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public FlowActionSalesforceSearchLeadsParams build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
