/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FlowActionHubspotEnrollContactAction {

    public static final FlowActionHubspotEnrollContactAction ENROLL_CONTACT = new FlowActionHubspotEnrollContactAction(Value.ENROLL_CONTACT, "ENROLL_CONTACT");

    private final Value value;

    private final String string;

    FlowActionHubspotEnrollContactAction(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FlowActionHubspotEnrollContactAction valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        ENROLL_CONTACT, UNKNOWN
    }

    public interface Visitor<T> {

        T visitEnrollContact();

        T visitUnknown(String unknownType);
    }
}
