/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FlowActionOtpVerifyCodeAction {

    public static final FlowActionOtpVerifyCodeAction VERIFY_CODE = new FlowActionOtpVerifyCodeAction(Value.VERIFY_CODE, "VERIFY_CODE");

    private final Value value;

    private final String string;

    FlowActionOtpVerifyCodeAction(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FlowActionOtpVerifyCodeAction valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        VERIFY_CODE, UNKNOWN
    }

    public interface Visitor<T> {

        T visitVerifyCode();

        T visitUnknown(String unknownType);
    }
}
