/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowsVaultConnectioSetupSecretApiKey.Builder.class)
public final class FlowsVaultConnectioSetupSecretApiKey {

    private final FlowsVaultConnectioSetupTypeApiKeyEnum type;

    private final String secretKey;

    private final Map<String, Object> additionalProperties;

    private FlowsVaultConnectioSetupSecretApiKey(FlowsVaultConnectioSetupTypeApiKeyEnum type, String secretKey, Map<String, Object> additionalProperties) {
        this.type = type;
        this.secretKey = secretKey;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public FlowsVaultConnectioSetupTypeApiKeyEnum getType() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("secret_key")
    public String getSecretKey() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FlowsVaultConnectioSetupSecretApiKey other) {
        return type.equals(other.type) && secretKey.equals(other.secretKey);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static TypeStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface TypeStage {

        SecretKeyStage type(@NotNull FlowsVaultConnectioSetupTypeApiKeyEnum type);

        Builder from(FlowsVaultConnectioSetupSecretApiKey other);
    }

    public interface SecretKeyStage {

        _FinalStage secretKey(@NotNull String secretKey);
    }

    public interface _FinalStage {

        FlowsVaultConnectioSetupSecretApiKey build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, SecretKeyStage, _FinalStage {

        private FlowsVaultConnectioSetupTypeApiKeyEnum type;

        private String secretKey;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(FlowsVaultConnectioSetupSecretApiKey other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("type")
        public SecretKeyStage type(@NotNull FlowsVaultConnectioSetupTypeApiKeyEnum type) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("secret_key")
        public _FinalStage secretKey(@NotNull String secretKey) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public FlowsVaultConnectioSetupSecretApiKey build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
