/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FormBlockResendButtonConfig.Builder.class)
public final class FormBlockResendButtonConfig {

    private final String activeText;

    private final String buttonText;

    private final String waitingText;

    private final Optional<FormBlockResendButtonConfigTextAlignmentEnum> textAlignment;

    private final String flowId;

    private final Optional<Double> maxAttempts;

    private final Optional<Double> waitingTime;

    private final Map<String, Object> additionalProperties;

    private FormBlockResendButtonConfig(String activeText, String buttonText, String waitingText, Optional<FormBlockResendButtonConfigTextAlignmentEnum> textAlignment, String flowId, Optional<Double> maxAttempts, Optional<Double> waitingTime, Map<String, Object> additionalProperties) {
        this.activeText = activeText;
        this.buttonText = buttonText;
        this.waitingText = waitingText;
        this.textAlignment = textAlignment;
        this.flowId = flowId;
        this.maxAttempts = maxAttempts;
        this.waitingTime = waitingTime;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("active_text")
    public String getActiveText() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("button_text")
    public String getButtonText() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("waiting_text")
    public String getWaitingText() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("text_alignment")
    public Optional<FormBlockResendButtonConfigTextAlignmentEnum> getTextAlignment() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("flow_id")
    public String getFlowId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("max_attempts")
    public Optional<Double> getMaxAttempts() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("waiting_time")
    public Optional<Double> getWaitingTime() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FormBlockResendButtonConfig other) {
        return activeText.equals(other.activeText) && buttonText.equals(other.buttonText) && waitingText.equals(other.waitingText) && textAlignment.equals(other.textAlignment) && flowId.equals(other.flowId) && maxAttempts.equals(other.maxAttempts) && waitingTime.equals(other.waitingTime);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static ActiveTextStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface ActiveTextStage {

        ButtonTextStage activeText(@NotNull String activeText);

        Builder from(FormBlockResendButtonConfig other);
    }

    public interface ButtonTextStage {

        WaitingTextStage buttonText(@NotNull String buttonText);
    }

    public interface WaitingTextStage {

        FlowIdStage waitingText(@NotNull String waitingText);
    }

    public interface FlowIdStage {

        _FinalStage flowId(@NotNull String flowId);
    }

    public interface _FinalStage {

        FormBlockResendButtonConfig build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage textAlignment(Optional<FormBlockResendButtonConfigTextAlignmentEnum> textAlignment);

        _FinalStage textAlignment(FormBlockResendButtonConfigTextAlignmentEnum textAlignment);

        _FinalStage maxAttempts(Optional<Double> maxAttempts);

        _FinalStage maxAttempts(Double maxAttempts);

        _FinalStage waitingTime(Optional<Double> waitingTime);

        _FinalStage waitingTime(Double waitingTime);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActiveTextStage, ButtonTextStage, WaitingTextStage, FlowIdStage, _FinalStage {

        private String activeText;

        private String buttonText;

        private String waitingText;

        private String flowId;

        private Optional<Double> waitingTime = Optional.empty();

        private Optional<Double> maxAttempts = Optional.empty();

        private Optional<FormBlockResendButtonConfigTextAlignmentEnum> textAlignment = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(FormBlockResendButtonConfig other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("active_text")
        public ButtonTextStage activeText(@NotNull String activeText) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("button_text")
        public WaitingTextStage buttonText(@NotNull String buttonText) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("waiting_text")
        public FlowIdStage waitingText(@NotNull String waitingText) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("flow_id")
        public _FinalStage flowId(@NotNull String flowId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage waitingTime(Double waitingTime) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "waiting_time", nulls = Nulls.SKIP)
        public _FinalStage waitingTime(Optional<Double> waitingTime) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage maxAttempts(Double maxAttempts) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "max_attempts", nulls = Nulls.SKIP)
        public _FinalStage maxAttempts(Optional<Double> maxAttempts) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public _FinalStage textAlignment(FormBlockResendButtonConfigTextAlignmentEnum textAlignment) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter(value = "text_alignment", nulls = Nulls.SKIP)
        public _FinalStage textAlignment(Optional<FormBlockResendButtonConfigTextAlignmentEnum> textAlignment) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public FormBlockResendButtonConfig build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
