/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FormWidgetRecaptchaConfig.Builder.class)
public final class FormWidgetRecaptchaConfig {

    private final String siteKey;

    private final String secretKey;

    private final Map<String, Object> additionalProperties;

    private FormWidgetRecaptchaConfig(String siteKey, String secretKey, Map<String, Object> additionalProperties) {
        this.siteKey = siteKey;
        this.secretKey = secretKey;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("site_key")
    public String getSiteKey() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("secret_key")
    public String getSecretKey() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FormWidgetRecaptchaConfig other) {
        return siteKey.equals(other.siteKey) && secretKey.equals(other.secretKey);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static SiteKeyStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface SiteKeyStage {

        SecretKeyStage siteKey(@NotNull String siteKey);

        Builder from(FormWidgetRecaptchaConfig other);
    }

    public interface SecretKeyStage {

        _FinalStage secretKey(@NotNull String secretKey);
    }

    public interface _FinalStage {

        FormWidgetRecaptchaConfig build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SiteKeyStage, SecretKeyStage, _FinalStage {

        private String siteKey;

        private String secretKey;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(FormWidgetRecaptchaConfig other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("site_key")
        public SecretKeyStage siteKey(@NotNull String siteKey) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        @JsonSetter("secret_key")
        public _FinalStage secretKey(@NotNull String secretKey) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public FormWidgetRecaptchaConfig build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
