/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FormFieldFileConfig.Builder.class)
public final class FormFieldFileConfig {

    private final Optional<Boolean> multiple;

    private final Optional<FormFieldFileConfigStorage> storage;

    private final Optional<List<FormFieldFileConfigCategoryEnum>> categories;

    private final Optional<List<String>> extensions;

    private final Optional<Integer> maxSize;

    private final Optional<Integer> maxFiles;

    private final Map<String, Object> additionalProperties;

    private FormFieldFileConfig(Optional<Boolean> multiple, Optional<FormFieldFileConfigStorage> storage, Optional<List<FormFieldFileConfigCategoryEnum>> categories, Optional<List<String>> extensions, Optional<Integer> maxSize, Optional<Integer> maxFiles, Map<String, Object> additionalProperties) {
        this.multiple = multiple;
        this.storage = storage;
        this.categories = categories;
        this.extensions = extensions;
        this.maxSize = maxSize;
        this.maxFiles = maxFiles;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("multiple")
    public Optional<Boolean> getMultiple() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("storage")
    public Optional<FormFieldFileConfigStorage> getStorage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("categories")
    public Optional<List<FormFieldFileConfigCategoryEnum>> getCategories() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("extensions")
    public Optional<List<String>> getExtensions() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("maxSize")
    public Optional<Integer> getMaxSize() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("maxFiles")
    public Optional<Integer> getMaxFiles() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FormFieldFileConfig other) {
        return multiple.equals(other.multiple) && storage.equals(other.storage) && categories.equals(other.categories) && extensions.equals(other.extensions) && maxSize.equals(other.maxSize) && maxFiles.equals(other.maxFiles);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<Boolean> multiple = Optional.empty();

        private Optional<FormFieldFileConfigStorage> storage = Optional.empty();

        private Optional<List<FormFieldFileConfigCategoryEnum>> categories = Optional.empty();

        private Optional<List<String>> extensions = Optional.empty();

        private Optional<Integer> maxSize = Optional.empty();

        private Optional<Integer> maxFiles = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(FormFieldFileConfig other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "multiple", nulls = Nulls.SKIP)
        public Builder multiple(Optional<Boolean> multiple) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder multiple(Boolean multiple) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "storage", nulls = Nulls.SKIP)
        public Builder storage(Optional<FormFieldFileConfigStorage> storage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder storage(FormFieldFileConfigStorage storage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "categories", nulls = Nulls.SKIP)
        public Builder categories(Optional<List<FormFieldFileConfigCategoryEnum>> categories) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder categories(List<FormFieldFileConfigCategoryEnum> categories) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "extensions", nulls = Nulls.SKIP)
        public Builder extensions(Optional<List<String>> extensions) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder extensions(List<String> extensions) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "maxSize", nulls = Nulls.SKIP)
        public Builder maxSize(Optional<Integer> maxSize) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder maxSize(Integer maxSize) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "maxFiles", nulls = Nulls.SKIP)
        public Builder maxFiles(Optional<Integer> maxFiles) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder maxFiles(Integer maxFiles) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public FormFieldFileConfig build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
