/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FormFieldPaymentConfigChargeOneOffCurrencyEnum {

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum CAD = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.CAD, "CAD");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum AUD = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.AUD, "AUD");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum USD = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.USD, "USD");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum EUR = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.EUR, "EUR");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum INR = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.INR, "INR");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum CHF = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.CHF, "CHF");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum GBP = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.GBP, "GBP");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum SEK = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.SEK, "SEK");

    public static final FormFieldPaymentConfigChargeOneOffCurrencyEnum MXN = new FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value.MXN, "MXN");

    private final Value value;

    private final String string;

    FormFieldPaymentConfigChargeOneOffCurrencyEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FormFieldPaymentConfigChargeOneOffCurrencyEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        AUD,
        CAD,
        CHF,
        EUR,
        GBP,
        INR,
        MXN,
        SEK,
        USD,
        UNKNOWN
    }

    public interface Visitor<T> {

        T visitAud();

        T visitCad();

        T visitChf();

        T visitEur();

        T visitGbp();

        T visitInr();

        T visitMxn();

        T visitSek();

        T visitUsd();

        T visitUnknown(String unknownType);
    }
}
