/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FormStepConfig.Builder.class)
public final class FormStepConfig {

    private final Optional<List<FormComponent>> components;

    private final Optional<FormNodePointer> nextNode;

    private final Map<String, Object> additionalProperties;

    private FormStepConfig(Optional<List<FormComponent>> components, Optional<FormNodePointer> nextNode, Map<String, Object> additionalProperties) {
        this.components = components;
        this.nextNode = nextNode;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("components")
    public Optional<List<FormComponent>> getComponents() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("next_node")
    public Optional<FormNodePointer> getNextNode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(FormStepConfig other) {
        return components.equals(other.components) && nextNode.equals(other.nextNode);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<List<FormComponent>> components = Optional.empty();

        private Optional<FormNodePointer> nextNode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(FormStepConfig other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "components", nulls = Nulls.SKIP)
        public Builder components(Optional<List<FormComponent>> components) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder components(List<FormComponent> components) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "next_node", nulls = Nulls.SKIP)
        public Builder nextNode(Optional<FormNodePointer> nextNode) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder nextNode(FormNodePointer nextNode) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public FormStepConfig build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
