/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListFlowsRequestParameters.Builder.class)
public final class ListFlowsRequestParameters {

    private final Optional<List<ListFlowsRequestParametersHydrateEnum>> hydrate;

    private final OptionalNullable<Integer> page;

    private final OptionalNullable<Integer> perPage;

    private final OptionalNullable<Boolean> includeTotals;

    private final OptionalNullable<Boolean> synchronous;

    private final Map<String, Object> additionalProperties;

    private ListFlowsRequestParameters(Optional<List<ListFlowsRequestParametersHydrateEnum>> hydrate, OptionalNullable<Integer> page, OptionalNullable<Integer> perPage, OptionalNullable<Boolean> includeTotals, OptionalNullable<Boolean> synchronous, Map<String, Object> additionalProperties) {
        this.hydrate = hydrate;
        this.page = page;
        this.perPage = perPage;
        this.includeTotals = includeTotals;
        this.synchronous = synchronous;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return hydration param
     */
    @JsonIgnore
    public Optional<List<ListFlowsRequestParametersHydrateEnum>> getHydrate() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Page index of the results to return. First page is 0.
     */
    @JsonIgnore
    public OptionalNullable<Integer> getPage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Number of results per page. Defaults to 50.
     */
    @JsonIgnore
    public OptionalNullable<Integer> getPerPage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Return results inside an object that contains the total result count (true) or as a direct array of results (false, default).
     */
    @JsonIgnore
    public OptionalNullable<Boolean> getIncludeTotals() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return flag to filter by sync/async flows
     */
    @JsonIgnore
    public OptionalNullable<Boolean> getSynchronous() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ListFlowsRequestParameters other) {
        return hydrate.equals(other.hydrate) && page.equals(other.page) && perPage.equals(other.perPage) && includeTotals.equals(other.includeTotals) && synchronous.equals(other.synchronous);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<List<ListFlowsRequestParametersHydrateEnum>> hydrate = Optional.empty();

        private OptionalNullable<Integer> page = OptionalNullable.absent();

        private OptionalNullable<Integer> perPage = OptionalNullable.absent();

        private OptionalNullable<Boolean> includeTotals = OptionalNullable.absent();

        private OptionalNullable<Boolean> synchronous = OptionalNullable.absent();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(ListFlowsRequestParameters other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>hydration param</p>
         */
        @JsonSetter(value = "hydrate", nulls = Nulls.SKIP)
        public Builder hydrate(@Nullable Optional<List<ListFlowsRequestParametersHydrateEnum>> hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder hydrate(List<ListFlowsRequestParametersHydrateEnum> hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder hydrate(com.auth0.client.mgmt.core.Nullable<List<ListFlowsRequestParametersHydrateEnum>> hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder hydrate(ListFlowsRequestParametersHydrateEnum hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Page index of the results to return. First page is 0.</p>
         */
        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(@Nullable OptionalNullable<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(Integer page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(Optional<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(com.auth0.client.mgmt.core.Nullable<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Number of results per page. Defaults to 50.</p>
         */
        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(@Nullable OptionalNullable<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(Integer perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(Optional<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(com.auth0.client.mgmt.core.Nullable<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Return results inside an object that contains the total result count (true) or as a direct array of results (false, default).</p>
         */
        @JsonSetter(value = "include_totals", nulls = Nulls.SKIP)
        public Builder includeTotals(@Nullable OptionalNullable<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(Boolean includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(Optional<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(com.auth0.client.mgmt.core.Nullable<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>flag to filter by sync/async flows</p>
         */
        @JsonSetter(value = "synchronous", nulls = Nulls.SKIP)
        public Builder synchronous(@Nullable OptionalNullable<Boolean> synchronous) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder synchronous(Boolean synchronous) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder synchronous(Optional<Boolean> synchronous) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder synchronous(com.auth0.client.mgmt.core.Nullable<Boolean> synchronous) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public ListFlowsRequestParameters build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
