/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.NullableNonemptyFilter;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListAculsResponseContentItem.Builder.class)
public final class ListAculsResponseContentItem {

    private final Optional<String> tenant;

    private final Optional<String> prompt;

    private final Optional<String> screen;

    private final Optional<AculRenderingModeEnum> renderingMode;

    private final OptionalNullable<List<AculContextConfigurationItem>> contextConfiguration;

    private final OptionalNullable<Boolean> defaultHeadTagsDisabled;

    private final OptionalNullable<Boolean> usePageTemplate;

    private final OptionalNullable<List<AculHeadTag>> headTags;

    private final OptionalNullable<AculFilters> filters;

    private final Map<String, Object> additionalProperties;

    private ListAculsResponseContentItem(Optional<String> tenant, Optional<String> prompt, Optional<String> screen, Optional<AculRenderingModeEnum> renderingMode, OptionalNullable<List<AculContextConfigurationItem>> contextConfiguration, OptionalNullable<Boolean> defaultHeadTagsDisabled, OptionalNullable<Boolean> usePageTemplate, OptionalNullable<List<AculHeadTag>> headTags, OptionalNullable<AculFilters> filters, Map<String, Object> additionalProperties) {
        this.tenant = tenant;
        this.prompt = prompt;
        this.screen = screen;
        this.renderingMode = renderingMode;
        this.contextConfiguration = contextConfiguration;
        this.defaultHeadTagsDisabled = defaultHeadTagsDisabled;
        this.usePageTemplate = usePageTemplate;
        this.headTags = headTags;
        this.filters = filters;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Tenant ID
     */
    @JsonProperty("tenant")
    public Optional<String> getTenant() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Name of the prompt
     */
    @JsonProperty("prompt")
    public Optional<String> getPrompt() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Name of the screen
     */
    @JsonProperty("screen")
    public Optional<String> getScreen() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Rendering mode
     */
    @JsonProperty("rendering_mode")
    public Optional<AculRenderingModeEnum> getRenderingMode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("context_configuration")
    public OptionalNullable<List<AculContextConfigurationItem>> getContextConfiguration() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Override Universal Login default head tags
     */
    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("default_head_tags_disabled")
    public OptionalNullable<Boolean> getDefaultHeadTagsDisabled() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Use page template with ACUL
     */
    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("use_page_template")
    public OptionalNullable<Boolean> getUsePageTemplate() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return An array of head tags
     */
    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("head_tags")
    public OptionalNullable<List<AculHeadTag>> getHeadTags() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("filters")
    public OptionalNullable<AculFilters> getFilters() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("context_configuration")
    private OptionalNullable<List<AculContextConfigurationItem>> _getContextConfiguration() {
        return contextConfiguration;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("default_head_tags_disabled")
    private OptionalNullable<Boolean> _getDefaultHeadTagsDisabled() {
        return defaultHeadTagsDisabled;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("use_page_template")
    private OptionalNullable<Boolean> _getUsePageTemplate() {
        return usePageTemplate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("head_tags")
    private OptionalNullable<List<AculHeadTag>> _getHeadTags() {
        return headTags;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("filters")
    private OptionalNullable<AculFilters> _getFilters() {
        return filters;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ListAculsResponseContentItem other) {
        return tenant.equals(other.tenant) && prompt.equals(other.prompt) && screen.equals(other.screen) && renderingMode.equals(other.renderingMode) && contextConfiguration.equals(other.contextConfiguration) && defaultHeadTagsDisabled.equals(other.defaultHeadTagsDisabled) && usePageTemplate.equals(other.usePageTemplate) && headTags.equals(other.headTags) && filters.equals(other.filters);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> tenant = Optional.empty();

        private Optional<String> prompt = Optional.empty();

        private Optional<String> screen = Optional.empty();

        private Optional<AculRenderingModeEnum> renderingMode = Optional.empty();

        private OptionalNullable<List<AculContextConfigurationItem>> contextConfiguration = OptionalNullable.absent();

        private OptionalNullable<Boolean> defaultHeadTagsDisabled = OptionalNullable.absent();

        private OptionalNullable<Boolean> usePageTemplate = OptionalNullable.absent();

        private OptionalNullable<List<AculHeadTag>> headTags = OptionalNullable.absent();

        private OptionalNullable<AculFilters> filters = OptionalNullable.absent();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(ListAculsResponseContentItem other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Tenant ID</p>
         */
        @JsonSetter(value = "tenant", nulls = Nulls.SKIP)
        public Builder tenant(Optional<String> tenant) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder tenant(String tenant) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Name of the prompt</p>
         */
        @JsonSetter(value = "prompt", nulls = Nulls.SKIP)
        public Builder prompt(Optional<String> prompt) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder prompt(String prompt) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Name of the screen</p>
         */
        @JsonSetter(value = "screen", nulls = Nulls.SKIP)
        public Builder screen(Optional<String> screen) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder screen(String screen) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Rendering mode</p>
         */
        @JsonSetter(value = "rendering_mode", nulls = Nulls.SKIP)
        public Builder renderingMode(Optional<AculRenderingModeEnum> renderingMode) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder renderingMode(AculRenderingModeEnum renderingMode) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "context_configuration", nulls = Nulls.SKIP)
        public Builder contextConfiguration(@Nullable OptionalNullable<List<AculContextConfigurationItem>> contextConfiguration) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder contextConfiguration(List<AculContextConfigurationItem> contextConfiguration) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder contextConfiguration(Optional<List<AculContextConfigurationItem>> contextConfiguration) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder contextConfiguration(com.auth0.client.mgmt.core.Nullable<List<AculContextConfigurationItem>> contextConfiguration) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Override Universal Login default head tags</p>
         */
        @JsonSetter(value = "default_head_tags_disabled", nulls = Nulls.SKIP)
        public Builder defaultHeadTagsDisabled(@Nullable OptionalNullable<Boolean> defaultHeadTagsDisabled) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder defaultHeadTagsDisabled(Boolean defaultHeadTagsDisabled) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder defaultHeadTagsDisabled(Optional<Boolean> defaultHeadTagsDisabled) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder defaultHeadTagsDisabled(com.auth0.client.mgmt.core.Nullable<Boolean> defaultHeadTagsDisabled) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Use page template with ACUL</p>
         */
        @JsonSetter(value = "use_page_template", nulls = Nulls.SKIP)
        public Builder usePageTemplate(@Nullable OptionalNullable<Boolean> usePageTemplate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder usePageTemplate(Boolean usePageTemplate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder usePageTemplate(Optional<Boolean> usePageTemplate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder usePageTemplate(com.auth0.client.mgmt.core.Nullable<Boolean> usePageTemplate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>An array of head tags</p>
         */
        @JsonSetter(value = "head_tags", nulls = Nulls.SKIP)
        public Builder headTags(@Nullable OptionalNullable<List<AculHeadTag>> headTags) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder headTags(List<AculHeadTag> headTags) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder headTags(Optional<List<AculHeadTag>> headTags) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder headTags(com.auth0.client.mgmt.core.Nullable<List<AculHeadTag>> headTags) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "filters", nulls = Nulls.SKIP)
        public Builder filters(@Nullable OptionalNullable<AculFilters> filters) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder filters(AculFilters filters) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder filters(Optional<AculFilters> filters) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder filters(com.auth0.client.mgmt.core.Nullable<AculFilters> filters) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public ListAculsResponseContentItem build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
