/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListLogsRequestParameters.Builder.class)
public final class ListLogsRequestParameters {

    private final OptionalNullable<Integer> page;

    private final OptionalNullable<Integer> perPage;

    private final OptionalNullable<String> sort;

    private final OptionalNullable<String> fields;

    private final OptionalNullable<Boolean> includeFields;

    private final OptionalNullable<Boolean> includeTotals;

    private final OptionalNullable<String> search;

    private final Map<String, Object> additionalProperties;

    private ListLogsRequestParameters(OptionalNullable<Integer> page, OptionalNullable<Integer> perPage, OptionalNullable<String> sort, OptionalNullable<String> fields, OptionalNullable<Boolean> includeFields, OptionalNullable<Boolean> includeTotals, OptionalNullable<String> search, Map<String, Object> additionalProperties) {
        this.page = page;
        this.perPage = perPage;
        this.sort = sort;
        this.fields = fields;
        this.includeFields = includeFields;
        this.includeTotals = includeTotals;
        this.search = search;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Page index of the results to return. First page is 0.
     */
    @JsonIgnore
    public OptionalNullable<Integer> getPage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Number of results per page. Paging is disabled if parameter not sent. Default: <code>50</code>. Max value: <code>100</code>
     */
    @JsonIgnore
    public OptionalNullable<Integer> getPerPage() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Field to use for sorting appended with <code>:1</code>  for ascending and <code>:-1</code> for descending. e.g. <code>date:-1</code>
     */
    @JsonIgnore
    public OptionalNullable<String> getSort() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Comma-separated list of fields to include or exclude (based on value provided for <code>include_fields</code>) in the result. Leave empty to retrieve all fields.
     */
    @JsonIgnore
    public OptionalNullable<String> getFields() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Whether specified fields are to be included (<code>true</code>) or excluded (<code>false</code>)
     */
    @JsonIgnore
    public OptionalNullable<Boolean> getIncludeFields() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Return results as an array when false (default). Return results inside an object that also contains a total result count when true.
     */
    @JsonIgnore
    public OptionalNullable<Boolean> getIncludeTotals() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return Retrieves logs that match the specified search criteria. This parameter can be combined with all the others in the /api/logs endpoint but is specified separately for clarity.
     * If no fields are provided a case insensitive 'starts with' search is performed on all of the following fields: client_name, connection, user_name. Otherwise, you can specify multiple fields and specify the search using the %field%:%search%, for example: application:node user:&quot;John@contoso.com&quot;.
     * Values specified without quotes are matched using a case insensitive 'starts with' search. If quotes are used a case insensitve exact search is used. If multiple fields are used, the AND operator is used to join the clauses.
     */
    @JsonIgnore
    public OptionalNullable<String> getSearch() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ListLogsRequestParameters other) {
        return page.equals(other.page) && perPage.equals(other.perPage) && sort.equals(other.sort) && fields.equals(other.fields) && includeFields.equals(other.includeFields) && includeTotals.equals(other.includeTotals) && search.equals(other.search);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private OptionalNullable<Integer> page = OptionalNullable.absent();

        private OptionalNullable<Integer> perPage = OptionalNullable.absent();

        private OptionalNullable<String> sort = OptionalNullable.absent();

        private OptionalNullable<String> fields = OptionalNullable.absent();

        private OptionalNullable<Boolean> includeFields = OptionalNullable.absent();

        private OptionalNullable<Boolean> includeTotals = OptionalNullable.absent();

        private OptionalNullable<String> search = OptionalNullable.absent();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(ListLogsRequestParameters other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Page index of the results to return. First page is 0.</p>
         */
        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(@Nullable OptionalNullable<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(Integer page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(Optional<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder page(com.auth0.client.mgmt.core.Nullable<Integer> page) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Number of results per page. Paging is disabled if parameter not sent. Default: <code>50</code>. Max value: <code>100</code></p>
         */
        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(@Nullable OptionalNullable<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(Integer perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(Optional<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder perPage(com.auth0.client.mgmt.core.Nullable<Integer> perPage) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Field to use for sorting appended with <code>:1</code>  for ascending and <code>:-1</code> for descending. e.g. <code>date:-1</code></p>
         */
        @JsonSetter(value = "sort", nulls = Nulls.SKIP)
        public Builder sort(@Nullable OptionalNullable<String> sort) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder sort(String sort) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder sort(Optional<String> sort) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder sort(com.auth0.client.mgmt.core.Nullable<String> sort) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Comma-separated list of fields to include or exclude (based on value provided for <code>include_fields</code>) in the result. Leave empty to retrieve all fields.</p>
         */
        @JsonSetter(value = "fields", nulls = Nulls.SKIP)
        public Builder fields(@Nullable OptionalNullable<String> fields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder fields(String fields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder fields(Optional<String> fields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder fields(com.auth0.client.mgmt.core.Nullable<String> fields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Whether specified fields are to be included (<code>true</code>) or excluded (<code>false</code>)</p>
         */
        @JsonSetter(value = "include_fields", nulls = Nulls.SKIP)
        public Builder includeFields(@Nullable OptionalNullable<Boolean> includeFields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeFields(Boolean includeFields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeFields(Optional<Boolean> includeFields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeFields(com.auth0.client.mgmt.core.Nullable<Boolean> includeFields) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Return results as an array when false (default). Return results inside an object that also contains a total result count when true.</p>
         */
        @JsonSetter(value = "include_totals", nulls = Nulls.SKIP)
        public Builder includeTotals(@Nullable OptionalNullable<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(Boolean includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(Optional<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder includeTotals(com.auth0.client.mgmt.core.Nullable<Boolean> includeTotals) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Retrieves logs that match the specified search criteria. This parameter can be combined with all the others in the /api/logs endpoint but is specified separately for clarity.
         * If no fields are provided a case insensitive 'starts with' search is performed on all of the following fields: client_name, connection, user_name. Otherwise, you can specify multiple fields and specify the search using the %field%:%search%, for example: application:node user:&quot;John@contoso.com&quot;.
         * Values specified without quotes are matched using a case insensitive 'starts with' search. If quotes are used a case insensitve exact search is used. If multiple fields are used, the AND operator is used to join the clauses.</p>
         */
        @JsonSetter(value = "search", nulls = Nulls.SKIP)
        public Builder search(@Nullable OptionalNullable<String> search) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder search(String search) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder search(Optional<String> search) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder search(com.auth0.client.mgmt.core.Nullable<String> search) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public ListLogsRequestParameters build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
