/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = NativeSocialLoginGoogle.Builder.class)
public final class NativeSocialLoginGoogle {

    private final Optional<Boolean> enabled;

    private final Map<String, Object> additionalProperties;

    private NativeSocialLoginGoogle(Optional<Boolean> enabled, Map<String, Object> additionalProperties) {
        this.enabled = enabled;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Determine whether or not to allow signing in natively using a Google ID token
     */
    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(NativeSocialLoginGoogle other) {
        return enabled.equals(other.enabled);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<Boolean> enabled = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(NativeSocialLoginGoogle other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Determine whether or not to allow signing in natively using a Google ID token</p>
         */
        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder enabled(Boolean enabled) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public NativeSocialLoginGoogle build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
