/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = NativeSocialLogin.Builder.class)
public final class NativeSocialLogin {

    private final Optional<NativeSocialLoginApple> apple;

    private final Optional<NativeSocialLoginFacebook> facebook;

    private final Optional<NativeSocialLoginGoogle> google;

    private final Map<String, Object> additionalProperties;

    private NativeSocialLogin(Optional<NativeSocialLoginApple> apple, Optional<NativeSocialLoginFacebook> facebook, Optional<NativeSocialLoginGoogle> google, Map<String, Object> additionalProperties) {
        this.apple = apple;
        this.facebook = facebook;
        this.google = google;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("apple")
    public Optional<NativeSocialLoginApple> getApple() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("facebook")
    public Optional<NativeSocialLoginFacebook> getFacebook() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonProperty("google")
    public Optional<NativeSocialLoginGoogle> getGoogle() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(NativeSocialLogin other) {
        return apple.equals(other.apple) && facebook.equals(other.facebook) && google.equals(other.google);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<NativeSocialLoginApple> apple = Optional.empty();

        private Optional<NativeSocialLoginFacebook> facebook = Optional.empty();

        private Optional<NativeSocialLoginGoogle> google = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(NativeSocialLogin other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "apple", nulls = Nulls.SKIP)
        public Builder apple(Optional<NativeSocialLoginApple> apple) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder apple(NativeSocialLoginApple apple) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "facebook", nulls = Nulls.SKIP)
        public Builder facebook(Optional<NativeSocialLoginFacebook> facebook) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder facebook(NativeSocialLoginFacebook facebook) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "google", nulls = Nulls.SKIP)
        public Builder google(Optional<NativeSocialLoginGoogle> google) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder google(NativeSocialLoginGoogle google) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public NativeSocialLogin build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
