/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class NetworkAclRuleScopeEnum {

    public static final NetworkAclRuleScopeEnum AUTHENTICATION = new NetworkAclRuleScopeEnum(Value.AUTHENTICATION, "authentication");

    public static final NetworkAclRuleScopeEnum MANAGEMENT = new NetworkAclRuleScopeEnum(Value.MANAGEMENT, "management");

    public static final NetworkAclRuleScopeEnum TENANT = new NetworkAclRuleScopeEnum(Value.TENANT, "tenant");

    public static final NetworkAclRuleScopeEnum DYNAMIC_CLIENT_REGISTRATION = new NetworkAclRuleScopeEnum(Value.DYNAMIC_CLIENT_REGISTRATION, "dynamic_client_registration");

    private final Value value;

    private final String string;

    NetworkAclRuleScopeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static NetworkAclRuleScopeEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        MANAGEMENT, AUTHENTICATION, TENANT, DYNAMIC_CLIENT_REGISTRATION, UNKNOWN
    }

    public interface Visitor<T> {

        T visitManagement();

        T visitAuthentication();

        T visitTenant();

        T visitDynamicClientRegistration();

        T visitUnknown(String unknownType);
    }
}
