/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OrganizationAccessLevelEnum {

    public static final OrganizationAccessLevelEnum READONLY = new OrganizationAccessLevelEnum(Value.READONLY, "readonly");

    public static final OrganizationAccessLevelEnum FULL = new OrganizationAccessLevelEnum(Value.FULL, "full");

    public static final OrganizationAccessLevelEnum LIMITED = new OrganizationAccessLevelEnum(Value.LIMITED, "limited");

    public static final OrganizationAccessLevelEnum NONE = new OrganizationAccessLevelEnum(Value.NONE, "none");

    private final Value value;

    private final String string;

    OrganizationAccessLevelEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OrganizationAccessLevelEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        NONE, READONLY, LIMITED, FULL, UNKNOWN
    }

    public interface Visitor<T> {

        T visitNone();

        T visitReadonly();

        T visitLimited();

        T visitFull();

        T visitUnknown(String unknownType);
    }
}
