/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RefreshTokenResourceServer.Builder.class)
public final class RefreshTokenResourceServer {

    private final Optional<String> audience;

    private final Optional<String> scopes;

    private final Map<String, Object> additionalProperties;

    private RefreshTokenResourceServer(Optional<String> audience, Optional<String> scopes, Map<String, Object> additionalProperties) {
        this.audience = audience;
        this.scopes = scopes;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Resource server ID
     */
    @JsonProperty("audience")
    public Optional<String> getAudience() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * @return List of scopes for the refresh token
     */
    @JsonProperty("scopes")
    public Optional<String> getScopes() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(RefreshTokenResourceServer other) {
        return audience.equals(other.audience) && scopes.equals(other.scopes);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> audience = Optional.empty();

        private Optional<String> scopes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(RefreshTokenResourceServer other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Resource server ID</p>
         */
        @JsonSetter(value = "audience", nulls = Nulls.SKIP)
        public Builder audience(Optional<String> audience) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder audience(String audience) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>List of scopes for the refresh token</p>
         */
        @JsonSetter(value = "scopes", nulls = Nulls.SKIP)
        public Builder scopes(Optional<String> scopes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder scopes(String scopes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public RefreshTokenResourceServer build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
