/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ResourceServerConsentPolicyEnum {

    public static final ResourceServerConsentPolicyEnum TRANSACTIONAL_AUTHORIZATION_WITH_MFA = new ResourceServerConsentPolicyEnum(Value.TRANSACTIONAL_AUTHORIZATION_WITH_MFA, "transactional-authorization-with-mfa");

    private final Value value;

    private final String string;

    ResourceServerConsentPolicyEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ResourceServerConsentPolicyEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        TRANSACTIONAL_AUTHORIZATION_WITH_MFA, UNKNOWN
    }

    public interface Visitor<T> {

        T visitTransactionalAuthorizationWithMfa();

        T visitUnknown(String unknownType);
    }
}
