/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResourceServerAuthorizationPolicy.Builder.class)
public final class ResourceServerAuthorizationPolicy {

    private final String policyId;

    private final Map<String, Object> additionalProperties;

    private ResourceServerAuthorizationPolicy(String policyId, Map<String, Object> additionalProperties) {
        this.policyId = policyId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The ID of the authorization policy to apply.
     */
    @JsonProperty("policy_id")
    public String getPolicyId() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(ResourceServerAuthorizationPolicy other) {
        return policyId.equals(other.policyId);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static PolicyIdStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface PolicyIdStage {

        /**
         * <p>The ID of the authorization policy to apply.</p>
         */
        _FinalStage policyId(@NotNull String policyId);

        Builder from(ResourceServerAuthorizationPolicy other);
    }

    public interface _FinalStage {

        ResourceServerAuthorizationPolicy build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PolicyIdStage, _FinalStage {

        private String policyId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(ResourceServerAuthorizationPolicy other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>The ID of the authorization policy to apply.</p>
         * <p>The ID of the authorization policy to apply.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("policy_id")
        public _FinalStage policyId(@NotNull String policyId) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public ResourceServerAuthorizationPolicy build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
