/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RotateConnectionKeysSigningAlgEnum {

    public static final RotateConnectionKeysSigningAlgEnum RS512 = new RotateConnectionKeysSigningAlgEnum(Value.RS512, "RS512");

    public static final RotateConnectionKeysSigningAlgEnum PS384 = new RotateConnectionKeysSigningAlgEnum(Value.PS384, "PS384");

    public static final RotateConnectionKeysSigningAlgEnum ES384 = new RotateConnectionKeysSigningAlgEnum(Value.ES384, "ES384");

    public static final RotateConnectionKeysSigningAlgEnum PS256 = new RotateConnectionKeysSigningAlgEnum(Value.PS256, "PS256");

    public static final RotateConnectionKeysSigningAlgEnum ES256 = new RotateConnectionKeysSigningAlgEnum(Value.ES256, "ES256");

    public static final RotateConnectionKeysSigningAlgEnum RS384 = new RotateConnectionKeysSigningAlgEnum(Value.RS384, "RS384");

    public static final RotateConnectionKeysSigningAlgEnum RS256 = new RotateConnectionKeysSigningAlgEnum(Value.RS256, "RS256");

    private final Value value;

    private final String string;

    RotateConnectionKeysSigningAlgEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RotateConnectionKeysSigningAlgEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        RS256,
        RS384,
        RS512,
        PS256,
        PS384,
        ES256,
        ES384,
        UNKNOWN
    }

    public interface Visitor<T> {

        T visitRs256();

        T visitRs384();

        T visitRs512();

        T visitPs256();

        T visitPs384();

        T visitEs256();

        T visitEs384();

        T visitUnknown(String unknownType);
    }
}
