/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SelfServiceProfileCustomTextPageEnum {

    public static final SelfServiceProfileCustomTextPageEnum GET_STARTED = new SelfServiceProfileCustomTextPageEnum(Value.GET_STARTED, "get-started");

    private final Value value;

    private final String string;

    SelfServiceProfileCustomTextPageEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SelfServiceProfileCustomTextPageEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        GET_STARTED, UNKNOWN
    }

    public interface Visitor<T> {

        T visitGetStarted();

        T visitUnknown(String unknownType);
    }
}
