/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SessionCookieMetadataModeEnum {

    public static final SessionCookieMetadataModeEnum NON_PERSISTENT = new SessionCookieMetadataModeEnum(Value.NON_PERSISTENT, "non-persistent");

    public static final SessionCookieMetadataModeEnum PERSISTENT = new SessionCookieMetadataModeEnum(Value.PERSISTENT, "persistent");

    private final Value value;

    private final String string;

    SessionCookieMetadataModeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <T> T visit(Visitor<T> visitor) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SessionCookieMetadataModeEnum valueOf(String value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public enum Value {

        NON_PERSISTENT, PERSISTENT, UNKNOWN
    }

    public interface Visitor<T> {

        T visitNonPersistent();

        T visitPersistent();

        T visitUnknown(String unknownType);
    }
}
