/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.Nullable;
import com.auth0.client.mgmt.core.NullableNonemptyFilter;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateFormRequestContent.Builder.class)
public final class UpdateFormRequestContent {

    private final Optional<String> name;

    private final OptionalNullable<FormMessages> messages;

    private final OptionalNullable<FormLanguages> languages;

    private final OptionalNullable<Map<String, Map<String, Object>>> translations;

    private final OptionalNullable<List<FormNode>> nodes;

    private final OptionalNullable<FormStartNode> start;

    private final OptionalNullable<FormEndingNode> ending;

    private final OptionalNullable<FormStyle> style;

    private final Map<String, Object> additionalProperties;

    private UpdateFormRequestContent(Optional<String> name, OptionalNullable<FormMessages> messages, OptionalNullable<FormLanguages> languages, OptionalNullable<Map<String, Map<String, Object>>> translations, OptionalNullable<List<FormNode>> nodes, OptionalNullable<FormStartNode> start, OptionalNullable<FormEndingNode> ending, OptionalNullable<FormStyle> style, Map<String, Object> additionalProperties) {
        this.name = name;
        this.messages = messages;
        this.languages = languages;
        this.translations = translations;
        this.nodes = nodes;
        this.start = start;
        this.ending = ending;
        this.style = style;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("messages")
    public OptionalNullable<FormMessages> getMessages() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("languages")
    public OptionalNullable<FormLanguages> getLanguages() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("translations")
    public OptionalNullable<Map<String, Map<String, Object>>> getTranslations() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("nodes")
    public OptionalNullable<List<FormNode>> getNodes() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("start")
    public OptionalNullable<FormStartNode> getStart() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("ending")
    public OptionalNullable<FormEndingNode> getEnding() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("style")
    public OptionalNullable<FormStyle> getStyle() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(UpdateFormRequestContent other) {
        return name.equals(other.name) && messages.equals(other.messages) && languages.equals(other.languages) && translations.equals(other.translations) && nodes.equals(other.nodes) && start.equals(other.start) && ending.equals(other.ending) && style.equals(other.style);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<String> name = Optional.empty();

        private OptionalNullable<FormMessages> messages = OptionalNullable.absent();

        private OptionalNullable<FormLanguages> languages = OptionalNullable.absent();

        private OptionalNullable<Map<String, Map<String, Object>>> translations = OptionalNullable.absent();

        private OptionalNullable<List<FormNode>> nodes = OptionalNullable.absent();

        private OptionalNullable<FormStartNode> start = OptionalNullable.absent();

        private OptionalNullable<FormEndingNode> ending = OptionalNullable.absent();

        private OptionalNullable<FormStyle> style = OptionalNullable.absent();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(UpdateFormRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder name(String name) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "messages", nulls = Nulls.SKIP)
        public Builder messages(OptionalNullable<FormMessages> messages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder messages(FormMessages messages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder messages(Optional<FormMessages> messages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder messages(Nullable<FormMessages> messages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "languages", nulls = Nulls.SKIP)
        public Builder languages(OptionalNullable<FormLanguages> languages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder languages(FormLanguages languages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder languages(Optional<FormLanguages> languages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder languages(Nullable<FormLanguages> languages) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "translations", nulls = Nulls.SKIP)
        public Builder translations(OptionalNullable<Map<String, Map<String, Object>>> translations) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder translations(Map<String, Map<String, Object>> translations) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder translations(Optional<Map<String, Map<String, Object>>> translations) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder translations(Nullable<Map<String, Map<String, Object>>> translations) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "nodes", nulls = Nulls.SKIP)
        public Builder nodes(OptionalNullable<List<FormNode>> nodes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder nodes(List<FormNode> nodes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder nodes(Optional<List<FormNode>> nodes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder nodes(Nullable<List<FormNode>> nodes) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "start", nulls = Nulls.SKIP)
        public Builder start(OptionalNullable<FormStartNode> start) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder start(FormStartNode start) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder start(Optional<FormStartNode> start) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder start(Nullable<FormStartNode> start) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "ending", nulls = Nulls.SKIP)
        public Builder ending(OptionalNullable<FormEndingNode> ending) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder ending(FormEndingNode ending) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder ending(Optional<FormEndingNode> ending) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder ending(Nullable<FormEndingNode> ending) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @JsonSetter(value = "style", nulls = Nulls.SKIP)
        public Builder style(OptionalNullable<FormStyle> style) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder style(FormStyle style) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder style(Optional<FormStyle> style) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder style(Nullable<FormStyle> style) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public UpdateFormRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
