/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.riskassessments.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateRiskAssessmentsSettingsRequestContent.Builder.class)
public final class UpdateRiskAssessmentsSettingsRequestContent {

    private final boolean enabled;

    private final Map<String, Object> additionalProperties;

    private UpdateRiskAssessmentsSettingsRequestContent(boolean enabled, Map<String, Object> additionalProperties) {
        this.enabled = enabled;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether or not risk assessment is enabled.
     */
    @JsonProperty("enabled")
    public boolean getEnabled() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(UpdateRiskAssessmentsSettingsRequestContent other) {
        return enabled == other.enabled;
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static EnabledStage builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public interface EnabledStage {

        /**
         * <p>Whether or not risk assessment is enabled.</p>
         */
        _FinalStage enabled(boolean enabled);

        Builder from(UpdateRiskAssessmentsSettingsRequestContent other);
    }

    public interface _FinalStage {

        UpdateRiskAssessmentsSettingsRequestContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EnabledStage, _FinalStage {

        private boolean enabled;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        @java.lang.Override
        public Builder from(UpdateRiskAssessmentsSettingsRequestContent other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Whether or not risk assessment is enabled.</p>
         * <p>Whether or not risk assessment is enabled.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("enabled")
        public _FinalStage enabled(boolean enabled) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public UpdateRiskAssessmentsSettingsRequestContent build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
