/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.riskassessments.settings;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.ManagementApiException;
import com.auth0.client.mgmt.core.ManagementApiHttpResponse;
import com.auth0.client.mgmt.core.ManagementException;
import com.auth0.client.mgmt.core.MediaTypes;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.errors.BadRequestError;
import com.auth0.client.mgmt.errors.ForbiddenError;
import com.auth0.client.mgmt.errors.NotFoundError;
import com.auth0.client.mgmt.errors.TooManyRequestsError;
import com.auth0.client.mgmt.errors.UnauthorizedError;
import com.auth0.client.mgmt.riskassessments.settings.types.UpdateRiskAssessmentsSettingsNewDeviceRequestContent;
import com.auth0.client.mgmt.types.GetRiskAssessmentsSettingsNewDeviceResponseContent;
import com.auth0.client.mgmt.types.UpdateRiskAssessmentsSettingsNewDeviceResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawNewDeviceClient {

    protected final ClientOptions clientOptions;

    public AsyncRawNewDeviceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Gets the risk assessment settings for the new device assessor
     */
    public CompletableFuture<ManagementApiHttpResponse<GetRiskAssessmentsSettingsNewDeviceResponseContent>> get() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Gets the risk assessment settings for the new device assessor
     */
    public CompletableFuture<ManagementApiHttpResponse<GetRiskAssessmentsSettingsNewDeviceResponseContent>> get(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Updates the risk assessment settings for the new device assessor
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateRiskAssessmentsSettingsNewDeviceResponseContent>> update(UpdateRiskAssessmentsSettingsNewDeviceRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Updates the risk assessment settings for the new device assessor
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateRiskAssessmentsSettingsNewDeviceResponseContent>> update(UpdateRiskAssessmentsSettingsNewDeviceRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
