/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.flows.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.types.GetFlowExecutionRequestParametersHydrateEnum;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetFlowExecutionRequestParameters.Builder.class)
public final class GetFlowExecutionRequestParameters {

    private final Optional<List<GetFlowExecutionRequestParametersHydrateEnum>> hydrate;

    private final Map<String, Object> additionalProperties;

    private GetFlowExecutionRequestParameters(Optional<List<GetFlowExecutionRequestParametersHydrateEnum>> hydrate, Map<String, Object> additionalProperties) {
        this.hydrate = hydrate;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Hydration param
     */
    @JsonIgnore
    public Optional<List<GetFlowExecutionRequestParametersHydrateEnum>> getHydrate() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private boolean equalTo(GetFlowExecutionRequestParameters other) {
        return hydrate.equals(other.hydrate);
    }

    @java.lang.Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @java.lang.Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static Builder builder() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {

        private Optional<List<GetFlowExecutionRequestParametersHydrateEnum>> hydrate = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
        }

        public Builder from(GetFlowExecutionRequestParameters other) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        /**
         * <p>Hydration param</p>
         */
        @JsonSetter(value = "hydrate", nulls = Nulls.SKIP)
        public Builder hydrate(@Nullable Optional<List<GetFlowExecutionRequestParametersHydrateEnum>> hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder hydrate(List<GetFlowExecutionRequestParametersHydrateEnum> hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder hydrate(com.auth0.client.mgmt.core.Nullable<List<GetFlowExecutionRequestParametersHydrateEnum>> hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder hydrate(GetFlowExecutionRequestParametersHydrateEnum hydrate) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public GetFlowExecutionRequestParameters build() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperty(String key, Object value) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
