/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.core;

import java.util.Optional;
import java.util.function.Function;

public final class Nullable<T> {

    private final Either<Optional<T>, Null> value;

    private Nullable() {
        this.value = Either.left(Optional.empty());
    }

    private Nullable(T value) {
        if (value == null) {
            this.value = Either.right(Null.INSTANCE);
        } else {
            this.value = Either.left(Optional.of(value));
        }
    }

    public static <T> Nullable<T> ofNull() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static <T> Nullable<T> of(T value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static <T> Nullable<T> empty() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public static <T> Nullable<T> ofOptional(Optional<T> value) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public boolean isNull() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public boolean isEmpty() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public T get() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public <U> Nullable<U> map(Function<? super T, ? extends U> mapper) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private static final class Either<L, R> {

        private L left = null;

        private R right = null;

        private Either(L left, R right) {
            if (left != null && right != null) {
                throw new IllegalArgumentException("Left and right argument cannot both be non-null.");
            }
            if (left == null && right == null) {
                throw new IllegalArgumentException("Left and right argument cannot both be null.");
            }
            if (left != null) {
                this.left = left;
            }
            if (right != null) {
                this.right = right;
            }
        }

        public static <L, R> Either<L, R> left(L left) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public static <L, R> Either<L, R> right(R right) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public boolean isLeft() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public boolean isRight() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public L getLeft() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        public R getRight() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }

    private static final class Null {

        private static final Null INSTANCE = new Null();

        private Null() {
        }
    }
}
