/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.connections;

import com.auth0.client.mgmt.connections.types.ListDirectoryProvisioningsRequestParameters;
import com.auth0.client.mgmt.connections.types.ListSynchronizedGroupsRequestParameters;
import com.auth0.client.mgmt.connections.types.ReplaceSynchronizedGroupsRequestContent;
import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.ManagementApiException;
import com.auth0.client.mgmt.core.ManagementApiHttpResponse;
import com.auth0.client.mgmt.core.ManagementException;
import com.auth0.client.mgmt.core.MediaTypes;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.auth0.client.mgmt.core.QueryStringMapper;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.errors.BadRequestError;
import com.auth0.client.mgmt.errors.ConflictError;
import com.auth0.client.mgmt.errors.ForbiddenError;
import com.auth0.client.mgmt.errors.NotFoundError;
import com.auth0.client.mgmt.errors.TooManyRequestsError;
import com.auth0.client.mgmt.errors.UnauthorizedError;
import com.auth0.client.mgmt.types.CreateDirectoryProvisioningRequestContent;
import com.auth0.client.mgmt.types.CreateDirectoryProvisioningResponseContent;
import com.auth0.client.mgmt.types.DirectoryProvisioning;
import com.auth0.client.mgmt.types.GetDirectoryProvisioningDefaultMappingResponseContent;
import com.auth0.client.mgmt.types.GetDirectoryProvisioningResponseContent;
import com.auth0.client.mgmt.types.ListDirectoryProvisioningsResponseContent;
import com.auth0.client.mgmt.types.ListSynchronizedGroupsResponseContent;
import com.auth0.client.mgmt.types.SynchronizedGroupPayload;
import com.auth0.client.mgmt.types.UpdateDirectoryProvisioningRequestContent;
import com.auth0.client.mgmt.types.UpdateDirectoryProvisioningResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawDirectoryProvisioningClient {

    protected final ClientOptions clientOptions;

    public AsyncRawDirectoryProvisioningClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve a list of directory provisioning configurations of a tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<DirectoryProvisioning>>> list() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve a list of directory provisioning configurations of a tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<DirectoryProvisioning>>> list(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve a list of directory provisioning configurations of a tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<DirectoryProvisioning>>> list(ListDirectoryProvisioningsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve a list of directory provisioning configurations of a tenant.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<DirectoryProvisioning>>> list(ListDirectoryProvisioningsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetDirectoryProvisioningResponseContent>> get(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetDirectoryProvisioningResponseContent>> get(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create a directory provisioning configuration for a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<CreateDirectoryProvisioningResponseContent>> create(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create a directory provisioning configuration for a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<CreateDirectoryProvisioningResponseContent>> create(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create a directory provisioning configuration for a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<CreateDirectoryProvisioningResponseContent>> create(String id, OptionalNullable<CreateDirectoryProvisioningRequestContent> request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create a directory provisioning configuration for a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<CreateDirectoryProvisioningResponseContent>> create(String id, OptionalNullable<CreateDirectoryProvisioningRequestContent> request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<Void>> delete(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Delete the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<Void>> delete(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateDirectoryProvisioningResponseContent>> update(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateDirectoryProvisioningResponseContent>> update(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateDirectoryProvisioningResponseContent>> update(String id, OptionalNullable<UpdateDirectoryProvisioningRequestContent> request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Update the directory provisioning configuration of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<UpdateDirectoryProvisioningResponseContent>> update(String id, OptionalNullable<UpdateDirectoryProvisioningRequestContent> request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the directory provisioning default attribute mapping of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetDirectoryProvisioningDefaultMappingResponseContent>> getDefaultMapping(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the directory provisioning default attribute mapping of a connection.
     */
    public CompletableFuture<ManagementApiHttpResponse<GetDirectoryProvisioningDefaultMappingResponseContent>> getDefaultMapping(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the configured synchronized groups for a connection directory provisioning configuration.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<SynchronizedGroupPayload>>> listSynchronizedGroups(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the configured synchronized groups for a connection directory provisioning configuration.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<SynchronizedGroupPayload>>> listSynchronizedGroups(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the configured synchronized groups for a connection directory provisioning configuration.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<SynchronizedGroupPayload>>> listSynchronizedGroups(String id, ListSynchronizedGroupsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve the configured synchronized groups for a connection directory provisioning configuration.
     */
    public CompletableFuture<ManagementApiHttpResponse<SyncPagingIterable<SynchronizedGroupPayload>>> listSynchronizedGroups(String id, ListSynchronizedGroupsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create or replace the selected groups for a connection directory provisioning configuration.
     */
    public CompletableFuture<ManagementApiHttpResponse<Void>> set(String id, ReplaceSynchronizedGroupsRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Create or replace the selected groups for a connection directory provisioning configuration.
     */
    public CompletableFuture<ManagementApiHttpResponse<Void>> set(String id, ReplaceSynchronizedGroupsRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
