/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.riskassessments;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.Suppliers;
import com.auth0.client.mgmt.riskassessments.settings.AsyncNewDeviceClient;
import com.auth0.client.mgmt.riskassessments.types.UpdateRiskAssessmentsSettingsRequestContent;
import com.auth0.client.mgmt.types.GetRiskAssessmentsSettingsResponseContent;
import com.auth0.client.mgmt.types.UpdateRiskAssessmentsSettingsResponseContent;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncSettingsClient {

    protected final ClientOptions clientOptions;

    private final AsyncRawSettingsClient rawClient;

    protected final Supplier<AsyncNewDeviceClient> newDeviceClient;

    public AsyncSettingsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSettingsClient(clientOptions);
        this.newDeviceClient = Suppliers.memoize(() -> new AsyncNewDeviceClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSettingsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Gets the tenant settings for risk assessments
     */
    public CompletableFuture<GetRiskAssessmentsSettingsResponseContent> get() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Gets the tenant settings for risk assessments
     */
    public CompletableFuture<GetRiskAssessmentsSettingsResponseContent> get(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Updates the tenant settings for risk assessments
     */
    public CompletableFuture<UpdateRiskAssessmentsSettingsResponseContent> update(UpdateRiskAssessmentsSettingsRequestContent request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Updates the tenant settings for risk assessments
     */
    public CompletableFuture<UpdateRiskAssessmentsSettingsResponseContent> update(UpdateRiskAssessmentsSettingsRequestContent request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public AsyncNewDeviceClient newDevice() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
