/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.organizations;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.organizations.types.CreateOrganizationAllConnectionRequestParameters;
import com.auth0.client.mgmt.organizations.types.ListOrganizationAllConnectionsRequestParameters;
import com.auth0.client.mgmt.organizations.types.UpdateOrganizationConnectionRequestParameters;
import com.auth0.client.mgmt.types.CreateOrganizationAllConnectionResponseContent;
import com.auth0.client.mgmt.types.GetOrganizationAllConnectionResponseContent;
import com.auth0.client.mgmt.types.OrganizationAllConnectionPost;
import com.auth0.client.mgmt.types.UpdateOrganizationAllConnectionResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncConnectionsClient {

    protected final ClientOptions clientOptions;

    private final AsyncRawConnectionsClient rawClient;

    public AsyncConnectionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawConnectionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawConnectionsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<SyncPagingIterable<OrganizationAllConnectionPost>> list(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<SyncPagingIterable<OrganizationAllConnectionPost>> list(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<SyncPagingIterable<OrganizationAllConnectionPost>> list(String id, ListOrganizationAllConnectionsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<SyncPagingIterable<OrganizationAllConnectionPost>> list(String id, ListOrganizationAllConnectionsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<CreateOrganizationAllConnectionResponseContent> create(String id, CreateOrganizationAllConnectionRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<CreateOrganizationAllConnectionResponseContent> create(String id, CreateOrganizationAllConnectionRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<GetOrganizationAllConnectionResponseContent> get(String id, String connectionId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<GetOrganizationAllConnectionResponseContent> get(String id, String connectionId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<Void> delete(String id, String connectionId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<Void> delete(String id, String connectionId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<UpdateOrganizationAllConnectionResponseContent> update(String id, String connectionId) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<UpdateOrganizationAllConnectionResponseContent> update(String id, String connectionId, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<UpdateOrganizationAllConnectionResponseContent> update(String id, String connectionId, UpdateOrganizationConnectionRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public CompletableFuture<UpdateOrganizationAllConnectionResponseContent> update(String id, String connectionId, UpdateOrganizationConnectionRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
