/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.keys;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.types.GetSigningKeysResponseContent;
import com.auth0.client.mgmt.types.RevokedSigningKeysResponseContent;
import com.auth0.client.mgmt.types.RotateSigningKeysResponseContent;
import com.auth0.client.mgmt.types.SigningKeys;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncSigningClient {

    protected final ClientOptions clientOptions;

    private final AsyncRawSigningClient rawClient;

    public AsyncSigningClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSigningClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSigningClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve details of all the application signing keys associated with your tenant.
     */
    public CompletableFuture<List<SigningKeys>> list() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve details of all the application signing keys associated with your tenant.
     */
    public CompletableFuture<List<SigningKeys>> list(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Rotate the application signing key of your tenant.
     */
    public CompletableFuture<RotateSigningKeysResponseContent> rotate() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Rotate the application signing key of your tenant.
     */
    public CompletableFuture<RotateSigningKeysResponseContent> rotate(RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve details of the application signing key with the given ID.
     */
    public CompletableFuture<GetSigningKeysResponseContent> get(String kid) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve details of the application signing key with the given ID.
     */
    public CompletableFuture<GetSigningKeysResponseContent> get(String kid, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Revoke the application signing key with the given ID.
     */
    public CompletableFuture<RevokedSigningKeysResponseContent> revoke(String kid) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Revoke the application signing key with the given ID.
     */
    public CompletableFuture<RevokedSigningKeysResponseContent> revoke(String kid, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
