/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.users;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.types.ConnectedAccount;
import com.auth0.client.mgmt.users.types.GetUserConnectedAccountsRequestParameters;
import java.util.concurrent.CompletableFuture;

public class AsyncConnectedAccountsClient {

    protected final ClientOptions clientOptions;

    private final AsyncRawConnectedAccountsClient rawClient;

    public AsyncConnectedAccountsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawConnectedAccountsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawConnectedAccountsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all connected accounts associated with the user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all connected accounts associated with the user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all connected accounts associated with the user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list(String id, GetUserConnectedAccountsRequestParameters request) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Retrieve all connected accounts associated with the user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list(String id, GetUserConnectedAccountsRequestParameters request, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
