/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.users;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;

public class AuthenticatorsClient {

    protected final ClientOptions clientOptions;

    private final RawAuthenticatorsClient rawClient;

    public AuthenticatorsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAuthenticatorsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAuthenticatorsClient withRawResponse() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Remove all authenticators registered to a given user ID, such as OTP, email, phone, and push-notification. This action cannot be undone. For more information, review <a href="https://auth0.com/docs/secure/multi-factor-authentication/manage-mfa-auth0-apis/manage-authentication-methods-with-management-api">Manage Authentication Methods with Management API</a>.
     */
    public void deleteAll(String id) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Remove all authenticators registered to a given user ID, such as OTP, email, phone, and push-notification. This action cannot be undone. For more information, review <a href="https://auth0.com/docs/secure/multi-factor-authentication/manage-mfa-auth0-apis/manage-authentication-methods-with-management-api">Manage Authentication Methods with Management API</a>.
     */
    public void deleteAll(String id, RequestOptions requestOptions) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
